/* ES6/DOM4 polyfill for IE < 8 | @version 0.7 alpha-3 | MIT License | github.com/termi */
;(function() {
var k=void 0,l=!0,s=null,t=!1;function W(){return function(){}}
(function(d,y){function A(a){if(!("__isFixed"in a)){var b="button"in a&&a.button;a.__isFixed=l;if("click"===a.type||"dblclick"===a.type)a.detail===k&&(a.detail="click"===a.type?1:2),!a.button&&A.b!==k&&(b=A.b);y(a,X);a.defaultPrevented||(a.defaultPrevented=t);a.target||(a.target=a.srcElement||document);a.relatedTarget===k&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==s&&(a.pageX=a.clientX+Y()-(p.clientLeft||0),a.pageY=a.clientY+Z()-(p.clientTop||
0));!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new pa);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);"currentTarget"in a||(a.currentTarget=this);!a.attrName&&a.propertyName&&(a.attrName=ea.call(a.propertyName,".")[0]);return a}}function $(a){if(A!==k){var b=this._,e,h,g,d;if(!b.__stop_events__){e=[];h=[];d="_e_8vj"+(Ka?"-":"");if(!b||!b[d])if("__dom0__"in a)b||(b={}),b[d]||(b[d]={});else return;a||(a=window.event);if("__custom_event"in a)g=a;else if(!(g=a.__customEvent__))a.bubbles==
k&&(a.bubbles=l),a.cancelable==k&&(a.cancelable=l),g=a.__customEvent__=new v(a),g.initEvent(a.type,a.bubbles,a.cancelable),A.call(this,g),g.e=l,g.__custom_event=k;g.ietl9_event=a;a.currentTarget=this;b=b[d][g.type];"__dom0__"in a&&((b||(b=[]))[0]=a.__dom0__);if(b){for(var c in b)if(M(b,c)){d=b[c];var f;"object"===typeof d&&(f=d,d=d.handleEvent);try{if(d&&(g.result=D.call(d,f||this,g))===t)g.preventDefault(),g.stopPropagation()}catch(q){e.push(q),h.push(q.message),console&&console.error(q)}if(g.__stopNow)break}b[0]=
k;delete b[0];a.returnValue=g.returnValue;a.cancelBubble=g.cancelBubble;1==e.length?E(e[0]):1<e.length&&(h=Error("Multiple errors thrown : "+g.type+" :  : "+h.join("|")),h.f=e,E(h))}this===document&&(!g.cancelBubble&&3===g.eventPhase)&&($.call(this.defaultView,g),a.cancelBubble=l)}}}function N(){}function La(){var a=document.querySelectorAll("#z").constructor.prototype;if(a&&a!==Array.prototype)for(var b in fa)M(b,fa)&&(a[b]||(a[b]=function(){return aa.call(Array.prototype[b],Array.from(this),arguments)}))}
function ga(a){var b=this.__orig__createElement__(a);if(qa.test(a))return b;~Q.indexOf("|"+a+"|")||(ha.push(a),Q+=a+"|",(B.__orig__createElement__||B.createElement)(a));return B.appendChild(b)}function ia(a){var b=-1;if(a.createElement){for(;++b<ha.length;)a.createElement(ha[b]);a.createElement!==ga&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=ga)}return a}function Ma(a){var b=document.getElementById("ielt8_style_prev_for_behaviour"),e="";b&&(e=b.getAttribute("data-url")||
"",b.id="");e&&a.replace(" url("," url("+e+") url(");b=ra("style");b.id="ielt8_style_prev_for_behaviour";b.type="text/css";b.setAttribute("data-url",a.replace("{behavior:","").replace(")}",")"));b.styleSheet.cssText="*"+a;document.head.appendChild(b)}function sa(a,b,e,h,g,d){var c=a.match(Na),a=e||[],f=!!g,q=f&&(b={})||(!b?document:"length"in b?b[0]:b),m,r=0,i,w,j=Oa[c[1]||""]||0,u=2<j,v=c[2],z=!!v,y=c[3],A=!!y,B=c[4],C=!!B,I="*"===v,O,K,n,G,R,P,x,T,M,U,E,J,F,H,L,N,Q,S;z&&(v=I?k:v.replace("|",":").toUpperCase());
C&&(B=B.replace(ta," "),M=RegExp(B.replace(ja,ka)));if(U=c[5]){U=ea.call(U,"][");for(O=-1;G=U[++O];)if(G=U[O]=G.match(Pa),G[2]=Qa[G[2]],(F=G[3])&&" i"==F.substr(-2))F.substr(0,F.length-2),G[4]=l}if(c=c[6])c=c.match(Ra),P=Sa[c[1]],2>P&&c[2]&&(R=/\D/.test(c[2])?"even"===c[2]?[s,2]:"odd"===c[2]?[s,2,"%",1]:c[2].match(Ta):[s,0,"%",c[2]],N=P?"nodeIndexLast":"nodeIndex",Q=P?"lastChild":"firstChild",S=P?"previousSibling":"nextSibling");f&&(j=0);if(1==j)if(A){g=document.getElementsByName(y);E=[];for(O=-1;i=
g[++O];)i.id==y&&E.push(i);g=A=k}else z=t;f=(!("length"in b)||1===b.length)&&!h&&!U&&!c&&!z&&!C&&!A;do{switch(j){case 0:i=g[0];break;case 1:if(y)if(g=[],E.length)for(O=-1;i=E[++O];){if(q===document||q.contains(i))g.push(i),E.splice(O--,1)}else return a;else"BODY"===v&&9===q.nodeType?(g=[q.body],C=!!B,f=f&&!C):g=q.getElementsByTagName(v||"*");i=g[0];break;case 2:g=q.children;i=g[0];break;case 3:m=b[r+1];case 4:if(!(i=la(q)))continue}if(f)return g;q=0;if(i){do if((!I||1===i.nodeType)&&!(h&&(K=i.sourceIndex)in
e)){if(n=!(z&&(w=i.nodeName.toUpperCase())!==v||A&&i.id!==y||C&&(!i.className||!M.test(i.className)))){if(U){O=-1;for(L=i.attributes;n&&(G=U[++O])&&(n=(H=G[1])in L);)if(x=H in ua?ua[H](i):(x=L[H])&&(x.specified||H in Ua)&&""!==x.nodeValue?x.nodeValue:s,J=G[2],x===s){if(!(n=8==J))n=t}else switch(G[4]&&(x=x.toUpperCase()),T=G[3],J){case 1:n=!!x||""===x;break;case 2:n=x===T;break;case 3:case 8:n=RegExp("(^| +)"+T+"($| +)").test(x);8==J&&(n=!n);break;case 4:case 5:case 6:F=x.indexOf(T);n=6===J?~F:5===
J?F==x.length-T.length:!F;break;case 7:n=x===T||!!~x.indexOf(T+"-");break;case 9:n=!!~(" "+x.replace(Va," ")+" ").indexOf(" "+T+" ")}}if(n&&c)switch(P){case 0:case 1:if(!R[1]&&!R[3])break;H=i[N]||0;J=R[3]?("%"===R[2]?-1:1)*R[3]:0;F=R[1];if(H)n=!F?!(H+J):!((H+J)%F);else{n=t;w=i.parentNode[Q];do if(1==w.nodeType&&(w[N]=++H)&&i===w&&(!F?!(H+J):!((H+J)%F)))n=l;while(!n&&(w=w[S]))}break;case 2:case 3:for(w=i;(w=w.previousSibling)&&1!==w.nodeType;);n=!w;if(!n||3==P)break;case 4:n=!la(i);break;case 5:n=
"HTML"==(w||i.nodeName.toUpperCase());break;case 6:n=!i.firstChild;break;case 7:n=!!i.checked;break;case 8:n=i.lang==R||p.lang==R;break;case 9:case 10:n="disabled"in i&&"form"in i&&(10==P?i.disabled===l&&"hidden"!==i.type:i.disabled===t);break;case 11:n=i.parentNode.selectedIndex&&!!i.selected;break;case 12:n=!!~(i.textContent||i.data||i.innerText||i.nodeValue||i.value||"").indexOf(c[2]);break;case 13:case 14:n=ba.call(i,c[2]);13==P&&(n=!n);break;case 15:case 16:w||(w=i.nodeName.toUpperCase()),n=
("INPUT"==w||"TEXTAREA"==w||D.call(i,i.__getAttribute__||i.getAttribute,"contenteditable")!==s)&&!i.q,16==P&&(n=!n)}}if(n){if(d)return[i];h?a[K]=i:a.push(i)}w=k}while(i=u?4===j?k:i===m?k:la(i):g[++q])}i=k}while(q=b[++r]);return a}function ma(a,b,e){e||(e=this);var a=va.call(a.replace(Wa,"$1")),h=[],g,d,c,f=l,q=t,j,m=a.replace(Xa,"@=").replace(Ya,"-child\\($1%$2\\)").match(Za);for(g=e;a=m.shift();){d=m[1];c=!d||","===d.charAt(0);if(!q)if(f&&"nodeType"in e&&9===e.nodeType&&"BODY"===a.toUpperCase())g=
[e.body],c&&(h=g);else if(f&&":root"===a)g=[p],c&&(h=g);else if(g&&(!(e=g)||0===g.length))g=s,q=l;else{if(f=!(!c||!j&&!(d||1<e.length)))j=l;g=sa(a,e,c?h:[],f,s,b&&c)}if(f=c)!h.length&&g&&(j=t,h=wa(g)),g=s,e=this,q=t;if(!d||","===d)break}return j?wa(h):h}function ba(a){if(!a)return t;if("*"===a||this===p&&":root"===a||this===document.body&&"BODY"===a.toUpperCase())return l;var b,e,h=t,g,a=va.call(a);if(b=a.match($a))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return(h=!(e=b[2])||
this.className&&RegExp(e.replace(ta," ").replace(ja,ka)).test(this.className))&&!(e=b[1])||this.tagName&&this.tagName.toUpperCase()===e.toUpperCase()}else{if(ab.test(a)){e=ma.call(this.ownerDocument,a);for(g in e)if(M(e,g)&&(h=e[g]===this))return l;return t}e=sa(a,s,t,s,this,l);return e[0]===this}}function xa(){document.removeEventListener("DOMContentLoaded",xa);ca&&(document.readyState="interactive");K&&K()}function ya(){d.detachEvent("onload",ya);ca&&(document.readyState="complete");K&&K()}var z=
window.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||k;if(9>z){d.Element||((d.Element=ActiveXObject).prototype.ie=l);d.HTMLElement||(d.HTMLElement=d.Element);d.Node||(d.Node=d.Element);var r;d.DocumentFragment||(d.DocumentFragment=d.Document||d.HTMLDocument||(r=W(),r.prototype={},r));d.Document||(d.Document=d.DocumentFragment);d._={ielt9shims:[],orig_:d._};var j=d._.ielt9shims,na=document.createDocumentFragment,ra=document.createElement,za=document.createTextNode,
p=document.documentElement,E=function(a){throw a instanceof Error?a:Error(a);},Aa=function(a){var b=Object.create(DOMException.prototype);b.code=DOMException[a];b.message=a+": DOM Exception "+b.code;throw b;},Ba=function(a,b){for(var e in b)if(M(b,e)&&a[e]!==b[e])try{a[e]=b[e]}catch(h){}},va=String.prototype.trim||function(){for(var a=this.replace(bb,""),b=a.length;cb.test(a.charAt(--b)););return a.slice(0,b+1)},ea=String.prototype.split,db=String.prototype.substr,Ca=Array.prototype.slice,aa=Function.prototype.apply,
D=Function.prototype.call,I=Function.prototype.bind||function(a,b){var e=this,h=Ca.call(arguments,1);return function(){return aa.call(e,a,h.concat(Ca.call(arguments)))}},M=I.call(Function.prototype.call,Object.prototype.hasOwnProperty);r=document.createElement("p");var f=d.Node.prototype,m=d.Element.prototype,eb=r.contains||f.contains,pa=Date,fb=/^\<([\w\:\-]*)[\>\ ]/i,bb=/^\s+/,cb=/\s/,oa,c,C,fa="every filter forEach indexOf join lastIndexOf map reduce reduceRight reverse slice some toString".split(" "),
gb=/alpha\(opacity=([^\)]+)\)/,da=function(){var a=(this.filter||"").match(gb);return a?parseInt(a[1])/100+"":""},Da={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,e){"important"!=e?this.setAttribute(a,b):(e=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"),a=";"+a+":"+b+" !important;",this.cssText=e.test(this.cssText)?this.cssText.replace(e,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||
"").match(RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"))||[])[2]||""},item:W()},v,L,X,hb=1,ib=W(),Ka=t,Ea,Q="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|nav|output|progress|section|source|summary|time|video",ha=Q.split("|"),qa=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,
u,B,S,Fa,Y,Z;"CSS1Compat"===document.compatMode?(Y=function(){return p.scrollLeft},Z=function(){return p.scrollTop}):(Y=function(){return document.body.scrollTop},Z=function(){return document.body.scrollLeft});document.head||(document.head=document.getElementsByTagName("head")[0]);"defaultView"in document||(document.defaultView=document.parentWindow);c=t;try{c=isNaN.apply(s,{})}catch(lb){}c||(Function.prototype.apply=function(a,b){try{return b!=k?aa.call(this,a,b):aa.call(this,a)}catch(e){return(-2146823260!=
e.number||b.length===k||"string"===typeof b)&&E(e),aa.call(this,a,Array.from(b))}});"b"!=="ab".substr(-1)&&(String.prototype.substr=function(a,b){return db.call(this,0>a?0>(a=this.length+a)?0:a:a,b)});if("te".split(/(s)*/)[1]!=k||3!="1_1".split(/(_)/).length)oa=/()??/.exec("")[1]===k,String.prototype.split=function(a,b){var e=this;if(!(a instanceof RegExp))return a===k&&0===b?[]:ea.call(e,a,b);var h=[],g=0,d=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.r?"y":""),c=RegExp(a.source,d+"g"),f=s,q,j,
e=e+"";oa||(f=RegExp("^"+c.source+"$(?!\\s)",d));if(b===k||0>+b)b=Infinity;else if(b=Math.floor(+b),!b)return[];for(;q=c.exec(e);){d=q.index+q[0].length;if(d>g&&(h.push(e.slice(g,q.index)),!oa&&1<q.length&&q[0].replace(f,function(){for(var a=1,b=arguments,e=b.length-2;a<e;a++)b[a]===k&&(q[a]=k)}),1<q.length&&q.index<e.length&&h.push.apply(h,q.slice(1)),j=q[0].length,g=d,h.length>=b))break;c.lastIndex===q.index&&c.lastIndex++}g===e.length?(j||!c.test(""))&&h.push(""):h.push(e.slice(g));return h.length>
b?h.slice(0,b):h};d.DOMException||(c=(d.DOMException=W()).prototype=Error(),c.INDEX_SIZE_ERR=1,c.HIERARCHY_REQUEST_ERR=3,c.WRONG_DOCUMENT_ERR=4,c.INVALID_CHARACTER_ERR=5,c.NO_MODIFICATION_ALLOWED_ERR=7,c.NOT_FOUND_ERR=8,c.NOT_SUPPORTED_ERR=9,c.INVALID_STATE_ERR=11,c.SYNTAX_ERR=12,c.INVALID_MODIFICATION_ERR=13,c.NAMESPACE_ERR=14,c.INVALID_ACCESS_ERR=15,c.TYPE_MISMATCH_ERR=17);"pageXOffset"in d||j.push(function(){Object.defineProperty(d,"pageXOffset",{get:Y});Object.defineProperty(d,"pageYOffset",{get:Z})});
C=d.Event=function(){E("")};L={initEvent:function(a,b,e){(a==k||b==k||e==k)&&E("WRONG_ARGUMENTS_ERR");this.type=a;this.bubbles=b;this.cancelable=e;this.e=t;this.target=s;this.timeStamp||(this.timeStamp=+new pa)},initCustomEvent:function(a,b,e,h){L.initEvent.call(this,a,b,e);this.detail=h},initUIEvent:function(a,b,e,h,g){L.initCustomEvent.call(this,a,b,e,g);this.view=h},initMouseEvent:function(a,b,e,h,g,d,c,f,q,j,m,i,w,p,r){L.initUIEvent.call(this,a,b,e,h,g);this.screenX=d;this.screenY=c;this.clientX=
f;this.clientY=q;this.ctrlKey=j;this.altKey=m;this.shiftKey=i;this.metaKey=w;this.button=p;this.relatedTarget=r}};X=C.prototype={constructor:C,preventDefault:function(){this.cancelable!==t&&(v.a.call(this).returnValue=t,v.c.call(this),this.defaultPrevented=l)},stopPropagation:function(){v.a.call(this).cancelBubble=l;v.c.call(this)}};for(c in L)M(L,c)&&(X[c]=function(){L[arguments.callee.name].apply(this,arguments);Ba(this.ietl9_event,this)},X[c].name=c);v=function(a){this.ietl9_event=a;a.returnValue=
l;Ba(this,a)};v.a=function(){var a=this.ietl9_event;a===k?E("WRONG_THIS_ERR"):a===s&&(a=v.a.d);return a};v.a.d={};v.c=function(){this.ietl9_event&&(this.ietl9_event=s)};C=W();C.prototype=X;C=new C;C.constructor=v;v.prototype=C;document.addEventListener||(f.addEventListener=p.addEventListener=d.addEventListener=document.addEventListener=function(a,b,e){if("function"==typeof b||"object"===typeof b&&b.handleEvent){var h=this,g=h._,c=t;h==d&&(!("_"in document)||!("_e_8vj"in document._)||!(a in document._._e_8vj))&&
document.addEventListener(a,ib,e);g||(g=h._={});switch(a){case "DOMContentLoaded":if("complete"==document.readyState)return;h===d&&(h=document);c=l;if(!Ea){Ea=l;var f=function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(f,50);return}$.call(h,{type:a,isTrusted:l,__custom_event:k})};if("createEventObject"in document&&"doScroll"in document.documentElement)try{d.frameElement||f()}catch(j){}}break;case "load":"tagName"in h&&"SCRIPT"===h.tagName.toUpperCase()&&(c=l,h.onreadystatechange=
function(){"loaded"===h.readyState&&(h.onreadystatechange=s,h.attachEvent("onreadystatechange",I.call($,h,{type:a})))},a="readystatechange");break;case "DOMMouseScroll":a="mousewheel"}h.setInterval&&(h!=d&&!h.frameElement)&&(h=d);b.uuid||(b.uuid=++hb);if(!(e=g._h_9e2))e=g._h_9e2=I.call($,h);g._e_8vj||(g._e_8vj={});g._e_8vj[a]||(g._e_8vj[a]={},c||h.attachEvent("on"+a,e));g._e_8vj[a][b.uuid]=b}},f.addEventListener.__shim__=l,f.removeEventListener=p.removeEventListener=d.removeEventListener=document.removeEventListener=
function(a,b){var e=this._,h,g,c;if(!("function"!=typeof b||!b.uuid||!e))if(h=e._h_9e2){g=e._e_8vj&&e._e_8vj[a];delete g[b.uuid];for(c in g)if(M(g,c))return;this.detachEvent("on"+a,h);delete e._e_8vj[a];for(c in e._e_8vj)if(M(e._e_8vj,c))return;delete e._e_8vj}},f.removeEventListener.__shim__=l,document.attachEvent("onmousedown",function(){A.b=event.button}),document.attachEvent("onclick",function(){A.b=k}));document.dispatchEvent||(f.dispatchEvent=p.dispatchEvent=d.dispatchEvent=document.dispatchEvent=
function(a){if(!a.type)return l;a.returnValue||(a.returnValue=l);a.cancelBubble&&(a.cancelBubble=t);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===d||-2146827850===b.number&&!(a.bubbles=t)){a.__custom_event=l;for(var e=a.target=this,c="on"+a.type;!a.cancelBubble&&e;)(c in e&&"function"==typeof e[c]&&(a.__dom0__=e[c])||"_"in e&&"_e_8vj"in e._)&&$.call(e,a),e=a.bubbles?e===document?document.defaultView:e.parentNode:s,"__dom0__"in a&&(a.__dom0__=
k);return!a.cancelBubble}E(b)}},f.dispatchEvent.__shim__=l);document.createEvent||(document.createEvent=function(){return new v(document.createEventObject())});j.push(function(){function a(a){var b,e=this.nodeName.toUpperCase(),c,d,h,f,i,j,m,p;if(!("INPUT"!=e&&"TEXTAREA"!=e)){j=document.activeElement;b=document.selection;this._&&(m=this._.__stop_events__,this._.__stop_events__=l);j._&&(p=j._.__stop_events__,j._.__stop_events__=l);try{this.focus(),c=b.createRange(),d=c.duplicate(),"TEXTAREA"==e?(h=
this.value,c=d,a?(c.moveEnd("character",h.length),i=""==c.text?h.length:h.lastIndexOf(c.text)):(c.moveStart("character",-h.length),i=c.text.length)):(d.moveToElementText(this),d.setEndPoint("EndToEnd",c),f=d.text.length-c.text.length,i=a?f:f+c.text.length),j&&j.focus&&j.focus()}catch(r){i=k}this._&&!m&&delete this._.__stop_events__;j._&&!p&&delete j._.__stop_events__;return i}}function b(a,b){if(a!=k){b==k&&(b=a);var e=this.nodeName.toUpperCase();"INPUT"!=e&&"TEXTAREA"!=e||(e=this.createTextRange(),
e.collapse(l),e.moveStart("character",a),e.moveEnd("character",b-a),e.select())}}var e=d.HTMLTextAreaElement&&d.HTMLTextAreaElement.prototype,c={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,l)},set:function(e){b.call(this,e,a.call(this));return e}},selectionEnd:{get:function(){return a.call(this)},set:function(e){b.call(this,a.call(this,l),e);return e}}};Object.defineProperties(d.HTMLInputElement&&d.HTMLInputElement.prototype||m,c);e&&Object.defineProperties(e,c)});
N.prototype=[];c=new N;c.push(1);c.length?d.NodeList=N:(c=document.createElement("iframe"),c.style.display="none",(document.body||p).appendChild(c),c.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),N=d.NodeList);N.prototype.item=function(a){return this[a]};document.querySelectorAll&&La();document.doctype===s&&7<z&&j.push(function(){var a=document.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});Object.defineProperty(document,"doctype",{configurable:l,
enumerable:t,get:function(){return a}})});f.contains||(f.contains=eb);D.call(za,document,"").contains||(d.Text&&d.Text.prototype?j.push(I.call(y,s,Text.prototype,f)):document.createTextNode=function(a){a=D.call(za,this,a);a.contains=f.contains;return a});!D.call(na,document).contains&&(d.HTMLDocument&&d.HTMLDocument.prototype)&&j.push(I.call(y,s,d.HTMLDocument.prototype,f));"children"in r||j.push(function(){Object.defineProperty(m,"children",{get:function(){for(var a=[],b=this.firstChild;b;)1==b.nodeType&&
a.push(b),b=b.nextSibling;return a}})});j.push(function(){function a(a,e){var c;try{var d=a;"element"in d&&("defaults"in d&&"document"in d)&&(d=d.element);var f=d.getBoundingClientRect(),j=document.body;c=!p.contains(d)?e?f.left:f.top:e?f.left+Y()-(p.clientLeft||j.clientLeft||0):f.top+Z()-(p.clientTop||j.clientTop||0)}catch(m){c=a;d=0;for(f=e?"offsetLeft":"offsetTop";c;)d+=parseInt(c[f],10),c=c.offsetParent;c=d}return c}Object.defineProperties(m,{offsetLeft:{get:function(){return a(this,l)}},offsetTop:{get:function(){return a(this)}}})});
r.childElementCount==k&&j.push(function(){Object.defineProperties(m,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;return a}},nextElementSibling:{get:function(){for(var a=this;(a=a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=this;(a=a.previousSibling)&&1!=a.nodeType;);return a}}})});document.ELEMENT_NODE||
(c={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},y(document,c),y(f,c),y(d.Node,c));"textContent"in r||j.push(function(){Object.defineProperty(f,"textContent",{get:function(){if("innerText"in this)return this.innerText;if("data"in this&&this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in this&&this.replaceData&&this.replaceData(0,this.length,a);return a}})});"isEqualNode"in
r||(document.isEqualNode=p.isEqualNode=f.isEqualNode=function(a){var b,e;if(a===s||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return t;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=a.prefix||this.localName!=a.localName)return t;b=0;for(e=this.attributes.length;b<e;b++){var c=this.attributes[length],d=a.getAttributeNS(c.namespaceURI,c.localName);if(d===s||d.value!==c.value)return t}}if(7===a.nodeType&&
(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return t;b=0;for(e=a.childNodes.length;b<e;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===t)return t;return l});document.importNode||(document.importNode=function(a,b){switch(a.nodeType){case 1:var e=document.createElement(a.nodeName),c=a.attributes,d,f,j;if(c&&0<c.length){f=0;for(j=c.length;f<j;)c=a.attributes[f++],e.setAttribute(c.nodeName,a.getAttribute(c.nodeName))}if(b&&
(d=a.childNodes)&&0<d.length){f=0;for(j=d.length;f<j;)e.appendChild(document.importNode(d[f++],b))}return e;case 3:case 4:case 8:return document.createTextNode(a.nodeValue)}Aa("NOT_SUPPORTED_ERR");return s},document.importNode.shim=l);c="compareDocumentPosition";c in document||(j=u||"DOCUMENT_POSITION_",p[c]=document[c]=f[c]=function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&4)+(this.sourceIndex>
a.sourceIndex&&2):1)+0:0},u="DISCONNECTED",p[j+u]=document[j+u]=f[j+u]=1,u="PRECEDING",p[j+u]=document[j+u]=f[j+u]=2,u="FOLLOWING",p[j+u]=document[j+u]=f[j+u]=4,u="CONTAINS",p[j+u]=document[j+u]=f[j+u]=8,u="CONTAINED_BY",p[j+u]=document[j+u]=f[j+u]=16);d.getComputedStyle||(d.getComputedStyle=function(a){var b=a.currentStyle||a.runtimeStyle;"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=Da.getPropertyValue.bind(a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=function(){Aa("NO_MODIFICATION_ALLOWED_ERR")},
a.runtimeStyle.getPropertyPriority=function(){return""},a.runtimeStyle.item=Da.item);var e,c;(c=d.CSSStyleDeclaration)&&(c=c.prototype)&&(!("float"in b)||!("opacity"in b))?("float"in b||((e=Object.getOwnPropertyDescriptor(c,"float"))&&delete c["float"],Object.defineProperty(a.runtimeStyle,"float",{value:{valueOf:I.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},a)}}),e&&Object.defineProperty(c,"float",e)),"opacity"in b||((e=Object.getOwnPropertyDescriptor(c,"opacity"))&&
delete c.opacity,Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:I.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||da.call(this.style)||da.call(this.runtimeStyle)},a)}}),e&&Object.defineProperty(c,"opacity",e))):("float"in b||(a.runtimeStyle["float"]={valueOf:I.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},a)}),"opacity"in b||(a.runtimeStyle.opacity={valueOf:I.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||
da.call(this.style)||da.call(this.runtimeStyle)},a)}));return a.currentStyle});document.createDocumentFragment=function(){var a=D.call(na,this);d.DocumentFragment===d.Document&&y(a,d.DocumentFragment.prototype);return ia(a)};u=(r.innerHTML="<x-x></x-x>",1===r.childNodes.length&&1===r.childNodes[0].nodeType);Q="|"+Q+"|";ga.ielt9=l;B=ia(D.call(na,document));u||(ia(document),document.head.insertAdjacentHTML("beforeend","<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>"));
0===D.call(ra,document,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(S=B.appendChild("createElement"in B&&B.createElement("div")||B.ownerDocument.createElement("div")),Fa=8===z?r.cloneNode:8>z?f.cloneNode:k,f.cloneNode=function(a){var b,e;qa.test(this.nodeName)?b=D.call(this.__nativeCloneNode__||Fa,this,a):(S.innerHTML="",e=a?this.outerHTML:this.outerHTML.replace(this.innerHTML,""),S.innerHTML=e.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=S.firstChild,!b&&!a&&((e=e.match(fb))&&(e=
e[1]),e&&(B.createElement(e),S.innerHTML=e,b=S.firstChild)));return B.appendChild(b)});r=c=C=fa=u=k;if(f.ie||!(7<z)){var ca=!document.readyState,V=["/a.ielt8.htc"],z="{behavior:",Ga=[],Ha,Ia,Ja,K,jb=d.scrollTo,kb=d.scrollBy;for(c=V.length;0<=--c;)z+=' url("'+V[c]+'")';z+="}";ca&&(document.readyState="uninitialized");f.ielt8=l;d.__ielt8__wontfix=Ga;var ja=/\s*(\S+)\s*/g,ka="(?=(^|.*\\s)$1(\\s|$))",$a=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,Wa=/\s*([,>+~ ])\s*/g,Xa=/\~\=/g,Za=/(^[>+~ ]?|,|\>|\+|~| ).*?(?=[,>+~ ]|$)/g,
ta=/\./g,Va=/\s/g,Na=/^([,>+~ ])?([\|\*\w-]*)\#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?:\:(.+))?$/,Pa=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$\@!]?=)['"]?(.*?)['"]?)?\]?$/,Ra=/^([^(]+)(?:\((.+)\))?$/,Ya=/\-child\((\dn)\+(\d)\)/g,Ta=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,ab=/([,>+~ ])/,Oa={"":1," ":1,",":1,">":2,"~":3,"+":4},Qa={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},Sa={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,
selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16},ua={href:function(a){return D.call(a,a.__getAttribute__||a.getAttribute,"href",2)}},Ua={coords:1,id:1,name:1},wa=function(a){for(var b=a.length>>>0,e=new N,c=0;c<b;c++)c in a&&e.push(a[c]);return e},la=function(a){for(;(a=a.nextSibling)&&1!=a.nodeType;);return a};c="matchesSelector";p[c]||(m[c]=p[c]=ba);c="matches";p[c]||(m[c]=p[c]=ba);c="querySelectorAll";document[c]||(m[c]=p[c]=document[c]=function(a,b){return ma.call(this,
a,t,b)});c="querySelector";document[c]||(m[c]=p[c]=document[c]=function(a,b){return ma.call(this,a,l,b)[0]||s});c="getElementsByClassName";document[c]||(m[c]=p[c]=document[c]=function(a){for(var a=RegExp(a.replace(ja,ka)),b=this.all,c,d=-1,f=[];c=b[++d];)c.className&&a.test(c.className)&&f.push(c);return f});m.setAttribute=function(a,b,c){c==k&&(a=a.toUpperCase(),b+="",c=1);return Function.prototype.call.call(this.__setAttribute__,this,a,b,c)};m.getAttribute=function(a,b){var c=a.toUpperCase(),d,
f;if(f=b==k)c=a.toUpperCase(),b=1;d=D.call(this.__getAttribute__,this,c,b);d!==s?f&&(d+=""):!(c in this)&&"string"===typeof this[a]?(d=this[c]=this[a],this.__removeAttribute__(a),d+=""):d=s;return d};m.removeAttribute=function(a,b){var c;return b==k&&(b=1,c=a.toUpperCase(),!(c in this)&&this.getAttribute(a)!==s)?(delete this[c],l):D.call(this.__removeAttribute__,this,c||a,b)};f.hasAttribute||(f.hasAttribute=function(a){return this.getAttribute(a)!==s});r=function(a){return function(){return a}};f.g=
r(1);f.k=r(2);f.l=r(3);f.m=r(4);f.n=r(7);f.o=r(8);f.p=r(9);f.h=r(10);f.i=r(11);f.j=r(16);f.__ielt8__element_init__=function(){var a=this;a.element&&(a=a.element);"prepend"in a||(a.after=m.after,a.before=m.before,a.append=m.append,a.prepend=m.prepend,a.replace=m.replace,a.remove=m.remove);"isEqualNode"in a||(a.isEqualNode=f.isEqualNode);"compareDocumentPosition"in a||(a.compareDocumentPosition=f.compareDocumentPosition);"getElementsByClassName"in a||(a.getElementsByClassName=m.getElementsByClassName);
"addEventListener"in a||(a.addEventListener=d.addEventListener,a.removeEventListener=d.removeEventListener,a.dispatchEvent=d.dispatchEvent);"querySelector"in a||(a.querySelectorAll=m.querySelectorAll,a.querySelector=m.querySelector);"matchesSelector"in a||(a.matchesSelector=ba,a.matches=ba);"hasAttribute"in a||(a.hasAttribute=m.hasAttribute);"setSelectionRange"in a||(a.setSelectionRange=m.setSelectionRange);this.setAttribute!=m.setAttribute&&(this.__setAttribute__=this.setAttribute,this.__getAttribute__=
this.getAttribute,this.__removeAttribute__=this.removeAttribute,this.setAttribute=m.setAttribute,this.getAttribute=m.getAttribute,this.removeAttribute=m.removeAttribute);try{a.cloneNode!==f.cloneNode&&(a.__nativeCloneNode__=a.cloneNode,a.cloneNode=f.cloneNode),f.contains&&(a.contains=f.contains)}catch(b){Ga.push(a)}};Ja=f.__ielt8_Node_behavior_apply=function(a){for(c=V.length;0<=--c;)try{a.addBehavior(V[c])}catch(b){}};Ia=f.cloneNode;f.cloneNode=function(a){a=D.call(Ia||this.__nativeCloneNode__,this,
a);Ja(a);return a};Ha=document.createElement;document.createElement=function(a){a=D.call(Ha,document,a);for(c=V.length;0<=--c;)try{a.addBehavior(V[c])}catch(b){}return a};d.XMLHttpRequest||(d.XMLHttpRequest=function(){var a;try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){a=new ActiveXObject("Microsoft.XMLHTTP")}var c=a.send;a.send=function(){this.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");c.apply(this,arguments)}});!("pageXOffset"in d)&&d.attachEvent&&(d.pageXOffset=d.pageYOffset=
0,K="CSS1Compat"===document.compatMode?function(){d.scrollX=d.pageXOffset=document.body.parentNode.scrollLeft;d.scrollY=d.pageYOffset=document.body.parentNode.scrollTop}:function(){d.scrollX=d.pageXOffset=document.body.scrollLeft;d.scrollY=d.pageYOffset=document.body.scrollTop},d.attachEvent("onscroll",K),d.scroll=d.scrollTo=function(a,b){jb(a,b);K()},d.scrollBy=function(a,b){kb(a,b);K()});document.addEventListener("DOMContentLoaded",xa);d.attachEvent("onload",ya);Ma(z);ca=z=c=k}}})(window,function(d,
y){for(var A in y)Object.prototype.hasOwnProperty.call(y,A)&&!Object.prototype.hasOwnProperty.call(d,A)&&(d[A]=y[A]);return d});
})();
