/* ES6/DOM4 polyfill for IE8 | @version 0.7 final | MIT License | github.com/termi */
;(function() {
var j=void 0,l=!0,m=null,q=!1;function L(){return function(){}}
(function(d,u){function v(a){if(!("__isFixed"in a)){var b="button"in a&&a.button;a.__isFixed=l;if("click"===a.type||"dblclick"===a.type)a.detail===j&&(a.detail="click"===a.type?1:2),!a.button&&v.b!==j&&(b=v.b);u(a,B);a.defaultPrevented||(a.defaultPrevented=q);a.target||(a.target=a.srcElement||document);a.relatedTarget===j&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==m&&(a.pageX=a.clientX+M()-(n.clientLeft||0),a.pageY=a.clientY+N()-(n.clientTop||
0));!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new ba);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);"currentTarget"in a||(a.currentTarget=this);!a.attrName&&a.propertyName&&(a.attrName=ca.call(a.propertyName,".")[0]);return a}}function O(a){if(v!==j){var b=this._,c,f,i,d;if(!b.__stop_events__){c=[];f=[];d="_e_8vj"+(la?"-":"");if(!b||!b[d])if("__dom0__"in a)b||(b={}),b[d]||(b[d]={});else return;a||(a=window.event);if("__custom_event"in a)i=a;else if(!(i=a.__customEvent__))a.bubbles==
j&&(a.bubbles=l),a.cancelable==j&&(a.cancelable=l),i=a.__customEvent__=new t(a),i.initEvent(a.type,a.bubbles,a.cancelable),v.call(this,i),i.g=l,i.__custom_event=j;i.ietl9_event=a;a.currentTarget=this;b=b[d][i.type];"__dom0__"in a&&((b||(b=[]))[0]=a.__dom0__);if(b){for(var e in b)if(C(b,e)){d=b[e];var A;"object"===typeof d&&(A=d,d=d.handleEvent);try{if(d&&(i.result=y.call(d,A||this,i))===q)i.preventDefault(),i.stopPropagation()}catch(r){c.push(r),f.push(r.message),console&&console.error(r)}if(i.__stopNow)break}b[0]=
j;delete b[0];a.returnValue=i.returnValue;a.cancelBubble=i.cancelBubble;1==c.length?D(c[0]):1<c.length&&(f=Error("Multiple errors thrown : "+i.type+" :  : "+f.join("|")),f.h=c,D(f))}this===document&&(!i.cancelBubble&&3===i.eventPhase)&&(O.call(this.defaultView,i),a.cancelBubble=l)}}}function E(){}function ma(){var a=document.querySelectorAll("#z").constructor.prototype;if(a&&a!==Array.prototype)for(var b in R)C(b,R)&&(a[b]||(a[b]=function(){return P.call(Array.prototype[b],Array.from(this),arguments)}))}
function S(a){var b=this.__orig__createElement__(a);if(da.test(a))return b;~H.indexOf("|"+a+"|")||(T.push(a),H+=a+"|",(w.__orig__createElement__||w.createElement)(a));return w.appendChild(b)}function U(a){var b=-1;if(a.createElement){for(;++b<T.length;)a.createElement(T[b]);a.createElement!==S&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=S)}return a}var Q=window.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||j;if(9>
Q){d.Element||((d.Element=ActiveXObject).prototype.ie=l);d.HTMLElement||(d.HTMLElement=d.Element);d.Node||(d.Node=d.Element);var s;d.DocumentFragment||(d.DocumentFragment=d.Document||d.HTMLDocument||(s=L(),s.prototype={},s));d.Document||(d.Document=d.DocumentFragment);d._={ielt9shims:[],orig_:d._};var g=d._.ielt9shims,V=document.createDocumentFragment,ea=document.createElement,fa=document.createTextNode,n=document.documentElement,D=function(a){throw a instanceof Error?a:Error(a);},ga=function(a){var b=
Object.create(DOMException.prototype);b.code=DOMException[a];b.message=a+": DOM Exception "+b.code;throw b;},ha=function(a,b){for(var c in b)if(C(b,c)&&a[c]!==b[c])try{a[c]=b[c]}catch(f){}},pa=String.prototype.trim||function(){for(var a=this.replace(na,""),b=a.length;oa.test(a.charAt(--b)););return a.slice(0,b+1)},ca=String.prototype.split,qa=String.prototype.substr,ia=Array.prototype.slice,P=Function.prototype.apply,y=Function.prototype.call,z=Function.prototype.bind||function(a,b){var c=this,f=
ia.call(arguments,1);return function(){return P.call(c,a,f.concat(ia.call(arguments)))}},C=z.call(Function.prototype.call,Object.prototype.hasOwnProperty);s=document.createElement("p");var h=d.Node.prototype,p=d.Element.prototype,ra=s.contains||h.contains,ba=Date,sa=/^\<([\w\:\-]*)[\>\ ]/i,na=/^\s+/,oa=/\s/,W,e,x,R="every filter forEach indexOf join lastIndexOf map reduce reduceRight reverse slice some toString".split(" "),X=/alpha\(opacity=([^\)]+)\)/,I=function(){var a=(this.filter||"").match(X);
return a?parseInt(a[1])/100+"":""},Y={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,c){"important"!=c?this.setAttribute(a,b):(c=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"),a=";"+a+":"+b+" !important;",this.cssText=c.test(this.cssText)?this.cssText.replace(c,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||"").match(RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))",
"i"))||[])[2]||""},item:L()},J={"for":"htmlFor","class":"className",value:"defaultValue"},Z={action:m,cite:m,codebase:m,data:m,href:m,longdesc:m,lowsrc:m,src:m,usemap:m},F={id:l,value:l,checked:l,disabled:l,ismap:l,multiple:l,readonly:l,selected:l},t,G,B,ta=1,ua=L(),la=q,ja,H="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|nav|output|progress|section|source|summary|time|video",T=H.split("|"),da=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,
k,w,K,ka,M,N;"CSS1Compat"===document.compatMode?(M=function(){return n.scrollLeft},N=function(){return n.scrollTop}):(M=function(){return document.body.scrollTop},N=function(){return document.body.scrollLeft});document.head||(document.head=document.getElementsByTagName("head")[0]);"defaultView"in document||(document.defaultView=document.parentWindow);e=q;try{e=isNaN.apply(m,{})}catch(xa){}e||(Function.prototype.apply=function(a,b){try{return b!=j?P.call(this,a,b):P.call(this,a)}catch(c){return(-2146823260!=
c.number||b.length===j||"string"===typeof b)&&D(c),P.call(this,a,Array.from(b))}});"b"!=="ab".substr(-1)&&(String.prototype.substr=function(a,b){return qa.call(this,0>a?0>(a=this.length+a)?0:a:a,b)});if("te".split(/(s)*/)[1]!=j||3!="1_1".split(/(_)/).length)W=/()??/.exec("")[1]===j,String.prototype.split=function(a,b){var c=this;if(!(a instanceof RegExp))return a===j&&0===b?[]:ca.call(c,a,b);var f=[],i=0,d=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.i?"y":""),e=RegExp(a.source,d+"g"),A=m,r,g,c=
c+"";W||(A=RegExp("^"+e.source+"$(?!\\s)",d));if(b===j||0>+b)b=Infinity;else if(b=Math.floor(+b),!b)return[];for(;r=e.exec(c);){d=r.index+r[0].length;if(d>i&&(f.push(c.slice(i,r.index)),!W&&1<r.length&&r[0].replace(A,function(){for(var a=1,b=arguments,c=b.length-2;a<c;a++)b[a]===j&&(r[a]=j)}),1<r.length&&r.index<c.length&&f.push.apply(f,r.slice(1)),g=r[0].length,i=d,f.length>=b))break;e.lastIndex===r.index&&e.lastIndex++}i===c.length?(g||!e.test(""))&&f.push(""):f.push(c.slice(i));return f.length>
b?f.slice(0,b):f};d.DOMException||(e=(d.DOMException=L()).prototype=Error(),e.INDEX_SIZE_ERR=1,e.HIERARCHY_REQUEST_ERR=3,e.WRONG_DOCUMENT_ERR=4,e.INVALID_CHARACTER_ERR=5,e.NO_MODIFICATION_ALLOWED_ERR=7,e.NOT_FOUND_ERR=8,e.NOT_SUPPORTED_ERR=9,e.INVALID_STATE_ERR=11,e.SYNTAX_ERR=12,e.INVALID_MODIFICATION_ERR=13,e.NAMESPACE_ERR=14,e.INVALID_ACCESS_ERR=15,e.TYPE_MISMATCH_ERR=17);"pageXOffset"in d||g.push(function(){Object.defineProperty(d,"pageXOffset",{get:M});Object.defineProperty(d,"pageYOffset",{get:N})});
x=d.Event=function(){D("")};G={initEvent:function(a,b,c){(a==j||b==j||c==j)&&D("WRONG_ARGUMENTS_ERR");this.type=a;this.bubbles=b;this.cancelable=c;this.g=q;this.target=m;this.timeStamp||(this.timeStamp=+new ba)},initCustomEvent:function(a,b,c,f){G.initEvent.call(this,a,b,c);this.detail=f},initUIEvent:function(a,b,c,f,i){G.initCustomEvent.call(this,a,b,c,i);this.view=f},initMouseEvent:function(a,b,c,f,i,d,e,A,r,g,k,h,n,p,s){G.initUIEvent.call(this,a,b,c,f,i);this.screenX=d;this.screenY=e;this.clientX=
A;this.clientY=r;this.ctrlKey=g;this.altKey=k;this.shiftKey=h;this.metaKey=n;this.button=p;this.relatedTarget=s}};B=x.prototype={constructor:x,preventDefault:function(){this.cancelable!==q&&(t.a.call(this).returnValue=this.returnValue=q,t.d.call(this),this.defaultPrevented=l)},stopPropagation:function(){t.a.call(this).cancelBubble=this.cancelBubble=l;t.d.call(this)}};B.stopImmediatePropagation=function(){this.__stopNow=l;this.stopPropagation()};B.defaultPrevented=q;for(e in G)C(G,e)&&(B[e]=function(){G[arguments.callee.name].apply(this,
arguments);ha(this.ietl9_event,this)},B[e].name=e);t=function(a){this.ietl9_event=a;a.returnValue=l;ha(this,a)};t.a=function(){var a=this.ietl9_event;a===j?D("WRONG_THIS_ERR"):a===m&&(a=t.a.f);return a};t.a.f={};t.d=function(){this.ietl9_event&&(this.ietl9_event=m)};x=L();x.prototype=B;x=new x;x.constructor=t;t.prototype=x;document.addEventListener||(h.addEventListener=n.addEventListener=d.addEventListener=document.addEventListener=function(a,b,c){if("function"==typeof b||"object"===typeof b&&b.handleEvent){var f=
this,i=f._,e=q;f==d&&(!("_"in document)||!("_e_8vj"in document._)||!(a in document._._e_8vj))&&document.addEventListener(a,ua,c);i||(i=f._={});switch(a){case "DOMContentLoaded":if("complete"==document.readyState)return;f===d&&(f=document);e=l;if(!ja){ja=l;var g=function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(g,50);return}O.call(f,{type:a,isTrusted:l,__custom_event:j})};if("createEventObject"in document&&"doScroll"in document.documentElement)try{d.frameElement||g()}catch(A){}}break;
case "load":"tagName"in f&&"SCRIPT"===f.tagName.toUpperCase()&&(e=l,f.onreadystatechange=function(){"loaded"===f.readyState&&(f.onreadystatechange=m,f.attachEvent("onreadystatechange",z.call(O,f,{type:a})))},a="readystatechange");break;case "DOMMouseScroll":a="mousewheel"}f.setInterval&&(f!=d&&!f.frameElement)&&(f=d);b.uuid||(b.uuid=++ta);if(!(c=i._h_9e2))c=i._h_9e2=z.call(O,f);i._e_8vj||(i._e_8vj={});i._e_8vj[a]||(i._e_8vj[a]={},e||f.attachEvent("on"+a,c));i._e_8vj[a][b.uuid]=b}},h.addEventListener.__shim__=
l,h.removeEventListener=n.removeEventListener=d.removeEventListener=document.removeEventListener=function(a,b){var c=this._,f,i,d;if(!("function"!=typeof b||!b.uuid||!c))if(f=c._h_9e2){i=c._e_8vj&&c._e_8vj[a];delete i[b.uuid];for(d in i)if(C(i,d))return;this.detachEvent("on"+a,f);delete c._e_8vj[a];for(d in c._e_8vj)if(C(c._e_8vj,d))return;delete c._e_8vj}},h.removeEventListener.__shim__=l,document.attachEvent("onmousedown",function(){v.b=event.button}),document.attachEvent("onclick",function(){v.b=
j}));document.dispatchEvent||(h.dispatchEvent=n.dispatchEvent=d.dispatchEvent=document.dispatchEvent=function(a){if(!a.type)return l;a.returnValue||(a.returnValue=l);a.cancelBubble&&(a.cancelBubble=q);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===d||-2146827850===b.number&&!(a.bubbles=q)){a.__custom_event=l;for(var c=a.target=this,f="on"+a.type;!a.cancelBubble&&c;)(f in c&&"function"==typeof c[f]&&(a.__dom0__=c[f])||"_"in c&&"_e_8vj"in c._)&&
O.call(c,a),c=a.bubbles?c===document?document.defaultView:c.parentNode:m,"__dom0__"in a&&(a.__dom0__=j);return!a.cancelBubble}D(b)}},h.dispatchEvent.__shim__=l);document.createEvent||(document.createEvent=function(){return new t(document.createEventObject())});g.push(function(){function a(a){var b,c=this.nodeName.toUpperCase(),f,d,e,g,k,h,n,p;if(!("INPUT"!=c&&"TEXTAREA"!=c)){h=document.activeElement;b=document.selection;this._&&(n=this._.__stop_events__,this._.__stop_events__=l);h._&&(p=h._.__stop_events__,
h._.__stop_events__=l);try{this.focus(),f=b.createRange(),d=f.duplicate(),"TEXTAREA"==c?(e=this.value,f=d,a?(f.moveEnd("character",e.length),k=""==f.text?e.length:e.lastIndexOf(f.text)):(f.moveStart("character",-e.length),k=f.text.length)):(d.moveToElementText(this),d.setEndPoint("EndToEnd",f),g=d.text.length-f.text.length,k=a?g:g+f.text.length),h&&h.focus&&h.focus()}catch(s){k=j}this._&&!n&&delete this._.__stop_events__;h._&&!p&&delete h._.__stop_events__;return k}}function b(a,b){if(a!=j){b==j&&
(b=a);var c=this.nodeName.toUpperCase();"INPUT"!=c&&"TEXTAREA"!=c||(c=this.createTextRange(),c.collapse(l),c.moveStart("character",a),c.moveEnd("character",b-a),c.select())}}var c=d.HTMLTextAreaElement&&d.HTMLTextAreaElement.prototype,f={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,l)},set:function(c){b.call(this,c,a.call(this));return c}},selectionEnd:{get:function(){return a.call(this)},set:function(c){b.call(this,a.call(this,l),c);return c}}};Object.defineProperties(d.HTMLInputElement&&
d.HTMLInputElement.prototype||p,f);c&&Object.defineProperties(c,f)});E.prototype=[];e=new E;e.push(1);e.length?d.NodeList=E:(e=document.createElement("iframe"),e.style.display="none",(document.body||n).appendChild(e),e.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),E=d.NodeList);E.prototype.item=function(a){return this[a]};document.querySelectorAll&&ma();document.doctype===m&&7<Q&&g.push(function(){var a=document.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});
Object.defineProperty(document,"doctype",{configurable:l,enumerable:q,get:function(){return a}})});h.contains||(h.contains=ra);y.call(fa,document,"").contains||(d.Text&&d.Text.prototype?g.push(z.call(u,m,Text.prototype,h)):document.createTextNode=function(a){a=y.call(fa,this,a);a.contains=h.contains;return a});!y.call(V,document).contains&&(d.HTMLDocument&&d.HTMLDocument.prototype)&&g.push(z.call(u,m,d.HTMLDocument.prototype,h));"children"in s||g.push(function(){Object.defineProperty(p,"children",
{get:function(){for(var a=[],b=this.firstChild;b;)1==b.nodeType&&a.push(b),b=b.nextSibling;return a}})});g.push(function(){function a(a,c){var f;try{a:{var d=a;"element"in d&&("defaults"in d&&"document"in d)&&(d=d.element);var e=d.getBoundingClientRect(),g,h,k;if((k=d.ownerDocument)!==document){if(g=k&&k.body,h=k&&k.documentElement,!g||!h){f=c?e.left:e.top;break a}}else g=document.body,h=n;f=c?e.left+M()-(h.clientLeft||g.clientLeft||0):e.top+N()-(h.clientTop||g.clientTop||0)}}catch(p){f=a;d=0;for(e=
c?"offsetLeft":"offsetTop";f;)d+=parseInt(f[e],10),f=f.offsetParent;f=d}return f}Object.defineProperties(p,{offsetLeft:{get:function(){return a(this,l)}},offsetTop:{get:function(){return a(this)}}})});s.childElementCount==j&&g.push(function(){Object.defineProperties(p,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;return a}},nextElementSibling:{get:function(){for(var a=
this;(a=a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=this;(a=a.previousSibling)&&1!=a.nodeType;);return a}}})});document.ELEMENT_NODE||(e={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},u(document,e),u(h,e),u(d.Node,e));"textContent"in s||g.push(function(){Object.defineProperty(h,"textContent",{get:function(){if("innerText"in this)return this.innerText;if("data"in
this&&this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in this&&this.replaceData&&this.replaceData(0,this.length,a);return a}})});"isEqualNode"in s||(document.isEqualNode=n.isEqualNode=h.isEqualNode=function(a){var b,c;if(a===m||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return q;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=a.prefix||this.localName!=a.localName)return q;
b=0;for(c=this.attributes.length;b<c;b++){var d=this.attributes[length],e=a.getAttributeNS(d.namespaceURI,d.localName);if(e===m||e.value!==d.value)return q}}if(7===a.nodeType&&(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return q;b=0;for(c=a.childNodes.length;b<c;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===q)return q;return l});document.importNode||(document.importNode=function(a,b){switch(a.nodeType){case 1:var c=
document.createElement(a.nodeName),d=a.attributes,e,g,h;if(d&&0<d.length){g=0;for(h=d.length;g<h;)d=a.attributes[g++],c.setAttribute(d.nodeName,a.getAttribute(d.nodeName))}if(b&&(e=a.childNodes)&&0<e.length){g=0;for(h=e.length;g<h;)c.appendChild(document.importNode(e[g++],b))}return c;case 3:case 4:case 8:return document.createTextNode(a.nodeValue)}ga("NOT_SUPPORTED_ERR");return m},document.importNode.shim=l);e="compareDocumentPosition";e in document||(g=k||"DOCUMENT_POSITION_",n[e]=document[e]=h[e]=
function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&4)+(this.sourceIndex>a.sourceIndex&&2):1)+0:0},k="DISCONNECTED",n[g+k]=document[g+k]=h[g+k]=1,k="PRECEDING",n[g+k]=document[g+k]=h[g+k]=2,k="FOLLOWING",n[g+k]=document[g+k]=h[g+k]=4,k="CONTAINS",n[g+k]=document[g+k]=h[g+k]=8,k="CONTAINED_BY",n[g+k]=document[g+k]=h[g+k]=16);d.getComputedStyle||(d.getComputedStyle=function(a){var b=a.currentStyle||
a.runtimeStyle;"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=Y.getPropertyValue.bind(a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=function(){ga("NO_MODIFICATION_ALLOWED_ERR")},a.runtimeStyle.getPropertyPriority=function(){return""},a.runtimeStyle.item=Y.item);var c,f;(f=d.CSSStyleDeclaration)&&(f=f.prototype)&&(!("float"in b)||!("opacity"in b))?("float"in b||((c=Object.getOwnPropertyDescriptor(f,"float"))&&delete f["float"],Object.defineProperty(a.runtimeStyle,"float",{value:{valueOf:z.call(function(){return this.runtimeStyle.styleFloat||
this.style.styleFloat},a)}}),c&&Object.defineProperty(f,"float",c)),"opacity"in b||((c=Object.getOwnPropertyDescriptor(f,"opacity"))&&delete f.opacity,Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:z.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||I.call(this.style)||I.call(this.runtimeStyle)},a)}}),c&&Object.defineProperty(f,"opacity",c))):("float"in b||(a.runtimeStyle["float"]={valueOf:z.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},
a)}),"opacity"in b||(a.runtimeStyle.opacity={valueOf:z.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||I.call(this.style)||I.call(this.runtimeStyle)},a)}));return a.currentStyle});document.createDocumentFragment=function(){var a=y.call(V,this);d.DocumentFragment===d.Document&&u(a,d.DocumentFragment.prototype);return U(a)};k=(s.innerHTML="<x-x></x-x>",1===s.childNodes.length&&1===s.childNodes[0].nodeType);H="|"+H+"|";S.ielt9=l;w=U(y.call(V,document));k||(U(document),document.head.insertAdjacentHTML("beforeend",
"<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>"));0===y.call(ea,document,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(K=w.appendChild("createElement"in w&&w.createElement("div")||w.ownerDocument.createElement("div")),ka=8===Q?s.cloneNode:8>Q?h.cloneNode:j,h.cloneNode=function(a){var b,c;da.test(this.nodeName)?b=y.call(this.__nativeCloneNode__||ka,this,a):(K.innerHTML="",c=a?this.outerHTML:this.outerHTML.replace(this.innerHTML,
""),K.innerHTML=c.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=K.firstChild,!b&&!a&&((c=c.match(sa))&&(c=c[1]),c&&(w.createElement(c),K.innerHTML=c,b=K.firstChild)));return w.appendChild(b)});var va=/\s+(?=\S)|^/g,$=p.getAttribute,wa=p.setAttribute,aa=p.removeAttribute;F.e={};F.c=function(a,b){if(b in this)return this[b];var c=a.nodeName;if(!(a=F.e[c]))a=F.e[c]=ea(c);c=$.call(a,b)!==m;c||(c=(c=a.constructor)&&(c=c.prototype)&&(c=Object.getOwnPropertyDescriptor(c,b))&&/\[native\scode\]/.test(c.get+
""));return this[b]=c};p.setAttribute=function(a,b){var c=a.toLowerCase();J[c]!==j?a=J[c]:Z[c]===j&&(0!==c.indexOf("data-")&&!F.c(this,c))&&(a=a.toUpperCase());return wa.call(this,a,b+"")};p.getAttribute=function(a){var b;b=a.toLowerCase();var c;if(J[b]!==j)return $.call(this,J[b]);if(Z[b]!==j)return(c=this.attributes)&&(c=c[b])&&(c=c.nodeValue)&&c+""||m;if(0!==b.indexOf("data-")&&!F.c(this,b))b=a.toUpperCase();else return $.call(this,a);c=this[b];c||(!(b in this)&&"string"===typeof this[a]?(c=this[b]=
this[a],delete this[a]):c=j);return c?c+"":m};p.removeAttribute=function(a){var b;b=a.toLowerCase();var c;if(J[b]!==j)return aa.call(this,J[b]);if(Z[b]===j&&0!==b.indexOf("data-")&&!F.c(this,b))b=a.toUpperCase();else return aa.call(this,a);if((c=b in this)||this.getAttribute(a)!==m)aa.call(this,b),delete this[b];return c};e="getElementsByClassName";!p[e]&&document.querySelectorAll&&(p[e]=n[e]=document[e]=function(a){return!a||!(a=pa.call(a))?new E:y.call(this.querySelectorAll||document.querySelectorAll,
this,a.replace(va,"."))});if(e=d.CSSStyleDeclaration)"opacity"in n.style||(Object.defineProperty(e.prototype,"opacity",{get:I,set:function(a){"object"==typeof a&&(a=a.valueOf());this.opacity!==I.call(this)&&delete this.opacity;a=a&&"alpha(opacity="+(0.9999<=a?"100":0>a?0:~~(100*a))+")"||"";this.filter=X.test(this.filter)?this.filter.replace(X,a):this.filter+(" "+a);this.msOpacity=this.opacity}}),Object.defineProperty(e.prototype,"msOpacity",{value:""})),"float"in n.style||Object.defineProperty(e.prototype,
"float",{get:function(){return this.styleFloat},set:function(a){return this.styleFloat=a}}),"getPropertyValue"in e||function(a){for(var b in a)C.call(a,b)&&(this[b]=a[b])}.call(e,Y);(function(a,b,c,d){function e(a){for(var b=a.length>>>0,c=new E,d=0;d<b;d++)d in a&&c.push(a[d]);return c}document.querySelectorAll=function(){return e(a.apply(this,arguments))};document.querySelector=function(){return b.apply(this,arguments)};p.querySelectorAll=function(){return e(c.apply(this,arguments))};p.querySelector=
function(){return d.apply(this,arguments)}})(document.querySelectorAll,document.querySelector,p.querySelectorAll,p.querySelector);s=e=x=R=k=j}})(window,function(d,u){for(var v in u)Object.prototype.hasOwnProperty.call(u,v)&&!Object.prototype.hasOwnProperty.call(d,v)&&(d[v]=u[v]);return d});
})();
