/* ES6/DOM4 polyfill for IE < 8 | @version 0.8.8 | MIT License | github.com/termi */
void function(D){var k=void 0,n=!0,p=null,q=!1;function Y(){return function(){}}function G(a){if(!("__isFixed"in a||a.isTrusted===q)){var b="button"in a&&a.button;a.__isFixed=n;if("click"===a.type||"dblclick"===a.type)a.detail===k&&(a.detail="click"===a.type?1:2),!a.button&&G.b!==k&&(b=G.b);D(a,L);a.defaultPrevented||(a.defaultPrevented=q);a.target||(a.target=a.srcElement||g);a.relatedTarget===k&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==p&&(a.pageX=a.clientX+da()-(r.clientLeft||0),a.pageY=a.clientY+
ea()-(r.clientTop||0));!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new Ca);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);a.keyCode||(a.keyCode=a.charCode||a.which);!a.attrName&&a.propertyName&&(a.attrName=ma.call(a.propertyName,".")[0]);return a}}function J(a){if(G!==k){var b=this._,c,e,h,d,fa,x,j,m;if(!b.__stop_events__){c=[];e=[];d="_e_8vj"+(Ua?"-":"");if(!b||!b[d])if("__dom0__"in a)b||(b={}),b[d]||(b[d]={});else return;a||(a=f.event);if("__custom_event"in a)h=
a;else if(!(h=a.__customEvent__))a.bubbles==k&&(a.bubbles=n),a.cancelable==k&&(a.cancelable=n),h=a.__customEvent__=new H(a),h.initEvent(a.type,a.bubbles,a.cancelable),h.h=a.h!==q,G.call(this,h),h.__custom_event=p;h.ietl9_event=a;h.currentTarget=this;"__dom0__"in a&&(x=a.__dom0__);if((b=b[d][h.type])||x)fa=b?ha.call(b):[],x&&fa.unshift(x);if(fa&&fa.length){for(;x=fa.shift();)if(x&&(!(m=x[O])||"_"+m in b)){"object"===typeof x&&(j=x,x=x.handleEvent);try{if(x&&(h.result=s.call(x,j||this,h))===q)h.defaultPrevented===
q&&h.returnValue!==q&&h.preventDefault(),h.stopPropagation()}catch(r){c.push(r),e.push(r.message)}if(h.__stopNow)break}a.returnValue=h.returnValue;a.cancelBubble=h.cancelBubble;1==c.length?Z(c[0]):1<c.length&&(e=Error("Multiple errors thrown : "+h.type+" :  : "+e.join("|")),e.errors=c,Z(e))}this===g&&(!h.cancelBubble&&3===h.eventPhase)&&(J.call(this.defaultView,h),a.cancelBubble=n);H.d.call(h);a.__customEvent__=p}}}function na(a){var b=(this.__orig__createElement__||ia)(a);if(Da.test(a))return b;
~$.indexOf("|"+a+"|")||(oa.push(a),$+=a+"|",(I.__orig__createElement__||I.createElement)(a));return I.appendChild(b)}function pa(a){var b=-1;if(a.createElement){for(;++b<oa.length;)a.createElement(oa[b]);a.createElement!==na&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=na)}return a}function Ea(a,b,c,e,h,f){var d=a.match(Va);a=c||[];var x=!!h,j=x&&(b={})||(!b?document:"length"in b&&!("nodeType"in b)&&!("childNodes"in b)?b[0]:b),m,u=0,l,z,y=Wa[d[1]||""]||
0,H=2<y,w=d[2],D=!!w,G=d[3],J=!!G,I=d[4],F=!!I,K="*"===w,E,M,t,N,B,R,v,C,Q,U,L,P,A,O,S,T;D&&(w=K?k:w.replace("|",":").toUpperCase());F&&(I=I.replace(Fa," "),Q=RegExp(I.replace(qa,ra)));if(U=d[5]){U=ma.call(U,"][");for(E=-1;N=U[++E];)if(N=U[E]=N.match(Xa),N[2]=Ya[N[2]],(A=N[3])&&" i"==A.substr(-2))A.substr(0,A.length-2),N[4]=n}if(d=d[6])d=d.match(Za),R=$a[d[1]],2>R&&d[2]&&(B=/\D/.test(d[2])?"even"===d[2]?[p,2]:"odd"===d[2]?[p,2,"%",1]:d[2].match(ab):[p,0,"%",d[2]],O=R?"nodeIndexLast":"nodeIndex",S=
R?"lastChild":"firstChild",T=R?"previousSibling":"nextSibling");x&&(y=0);if(1==y)if(J){h=g.getElementsByName(G);L=[];for(E=-1;l=h[++E];)l.id==G&&L.push(l);h=J=D=p}else w||(w="*",K=!F),D=q;x=(!("length"in b)||1===b.length)&&!e&&!U&&!d&&!D&&!F&&!J;do{switch(y){case 0:l=h[0];break;case 1:if(G)if(h=[],L.length)for(E=-1;l=L[++E];){if(j===g||j.contains(l))h.push(l),L.splice(E--,1)}else return a;else"BODY"===w&&9===j.nodeType?(h=[j.body],F=!!I,x=x&&!F):h=j.getElementsByTagName(w);l=h[0];break;case 2:h=j.children;
l=h[0];break;case 3:m=b[u+1];case 4:if(!(l=sa(j)))continue}if(x)return h;j=0;if(l){do if((!K||1===l.nodeType)&&!(e&&(M=l.sourceIndex)in c)){if(t=!(D&&(z=l.nodeName.toUpperCase())!==w||J&&l.id!==G||F&&(!l.className||!Q.test(l.className)))){if(U)for(E=-1;t&&(N=U[++E]);)if(P=N[2],A=l,v=N[1],v=v.toLowerCase(),v=V[v]!==k?A[V[v]]:ja[v]!==k?A.__getAttribute__(v,2):bb[v]!==k?A.__getAttribute__(v)?v:p:(A=A.getAttributeNode(v))&&A.value,v===p){if(!(t=8==P))t=q}else switch(N[4]&&(v=v.toUpperCase()),C=N[3],P){case 1:t=
!!v||""===v;break;case 2:t=v===C;break;case 3:case 8:t=RegExp("(^| +)"+C+"($| +)").test(v);8==P&&(t=!t);break;case 4:case 5:case 6:A=v.indexOf(C);t=6===P?~A:5===P?A==v.length-C.length:!A;break;case 7:t=v===C||!!~v.indexOf(C+"-");break;case 9:t=!!~(" "+v.replace(cb," ")+" ").indexOf(" "+C+" ")}if(t&&d)switch(R){case 0:case 1:if(!B[1]&&!B[3])break;E=l[O]||0;P=B[3]?("%"===B[2]?-1:1)*B[3]:0;A=B[1];if(E)t=!A?!(E+P):!((E+P)%A);else{t=q;z=l.parentNode[S];do if(1==z.nodeType&&(z[O]=++E)&&l===z&&(!A?!(E+P):
!((E+P)%A)))t=n;while(!t&&(z=z[T]))}break;case 2:case 3:for(z=l;(z=z.previousSibling)&&1!==z.nodeType;);t=!z;if(!t||3==R)break;case 4:t=!sa(l);break;case 5:t="HTML"==(z||l.nodeName.toUpperCase());break;case 6:t=!l.firstChild;break;case 7:t=!!l.checked;break;case 8:t=l.lang==B||r.lang==B;break;case 9:case 10:t="disabled"in l&&"form"in l&&(10==R?l.disabled===n&&"hidden"!==l.type:l.disabled===q);break;case 11:t=l.parentNode.selectedIndex&&!!l.selected;break;case 12:t=!!~(l.textContent||l.data||l.innerText||
l.nodeValue||l.value||"").indexOf(d[2]);break;case 13:case 14:t=ka.call(l,d[2]);13==R&&(t=!t);break;case 15:case 16:z||(z=l.nodeName.toUpperCase()),t=("INPUT"==z||"TEXTAREA"==z||s.call(l,l.__getAttribute__||l.getAttribute,"contenteditable")!==p)&&!l.v,16==R&&(t=!t)}}if(t){if(f)return[l];e?a[M]=l:a.push(l)}z=k}while(l=H?4===y?k:l===m?k:sa(l):h[++j])}l=k}while(j=b[++u]);return a}function ta(a,b,c){c||(c=this);a=Ga.call(a.replace(db,"$1"));var e=[],h,f,g,d=n,j=q,m,s=a.replace(eb,"@=").replace(fb,"-child\\($1%$2\\)").match(gb);
for(h=c;a=s.shift();){f=s[0];g=!f||","===f.charAt(0);if(!j)if(d&&"nodeType"in c&&9===c.nodeType&&"BODY"===a.toUpperCase())h=[c.body],g&&(e=h);else if(d&&":root"===a)h=[r],g&&(e=h);else if(h&&(!(c=h)||0===h.length))h=p,j=n;else{if(d=!(!g||!m&&!(f||1<c.length)))m=n;h=Ea(a,c,g?e:[],d,p,b&&g)}if(d=g)!e.length&&h&&(m=q,e=Ha(h)),h=p,c=this,j=q;if(!f||","===f)break}return m?Ha(e):e}function ka(a){if(!a)return q;if("*"===a||this===r&&":root"===a||this===g.body&&"BODY"===a.toUpperCase())return n;var b,c,e=
q,h;a=Ga.call(a);if(b=a.match(hb))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return(e=!(c=b[2])||this.className&&RegExp(c.replace(Fa," ").replace(qa,ra)).test(this.className))&&!(c=b[1])||this.tagName&&this.tagName.toUpperCase()===c.toUpperCase()}else{if(ib.test(a)){c=ta.call(this.ownerDocument,a);for(h in c)if(ga(c,h)&&(e=c[h]===this))return n;return q}c=Ea(a,p,q,p,[this],n);return c[0]===this}}function Ia(){g.removeEventListener("DOMContentLoaded",Ia);ua&&(g.readyState="interactive");
Q&&Q()}function Ja(){f.detachEvent("onload",Ja);ua&&(g.readyState="complete");Q&&Q()}var f=this,g=f.document,d,S="attachEvent"in g&&"all"in g&&"uniqueID"in g.documentElement&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||p;if(S&&!(9<S)){f.Element||((f.Element=f.ActiveXObject).prototype.ie=n);f.HTMLElement||(f.HTMLElement=f.Element);f.Node||(f.Node=f.Element);f.DocumentFragment||(f.DocumentFragment=f.Document||f.HTMLDocument||(d=Y(),d.prototype={},d));f.Document||(f.Document=f.DocumentFragment);
f._={ielt9shims:[],orig_:f._,isPlainObject:function(a){return a&&"[object Object]"===va.call(a)&&("function"===typeof a.constructor&&"[object Function]"===va.call(a.constructor)||a.__proto__===p)&&!ga(a,"callee")},apply:Function.prototype.apply};var B=f._.ielt9shims,wa=g.createDocumentFragment,ia=g.createElement,xa=g.createTextNode,r=g.documentElement,Z=function(a){throw"object"==typeof a&&a instanceof Error?a:Error(a);},Ka=function(a){var b=Object.create(DOMException.prototype);b.code=DOMException[a];
b.message=a+": DOM Exception "+b.code;throw b;},La=function(a,b){for(var c in b)if(ga(b,c)&&a[c]!==b[c])try{a[c]=b[c]}catch(e){}},Ga=String.prototype.trim||function(){for(var a=this.replace(jb,""),b=a.length;kb.test(a.charAt(--b)););return a.slice(0,b+1)},ma=String.prototype.split,lb=String.prototype.substr,ha=Array.prototype.slice,mb=Array.prototype.splice,nb=function(a){var b,c=a.length>>>0,e;try{if(b=ha.call(a),b.length===c)return b}catch(h){}b=[];for(e=0;e<c;e++)e in a&&(b[e]=a[e]);return b},
la=Function.prototype.apply,s=Function.prototype.call,F=Function.prototype.bind||function(a,b){var c=this,e;return 1<arguments.length?(e=ha.call(arguments,1),function(){return la.call(c,a,e.concat(ha.call(arguments)))}):function(){return la.call(c,a,arguments)}},va=Object.prototype.toString,ga=F.call(s,Object.prototype.hasOwnProperty),w=g.createElement("p"),j=f.Node.prototype,m=f.Element.prototype,ob=w.contains||j.contains,Ca=Date,pb=/^\<([\w\:\-]*)[\>\ ]/i,jb=/^\s+/,kb=/\s/,ya,K,qb=/alpha\(opacity=([^\)]+)\)/,
Ma=function(){var a=(this.filter||"").match(qb);return a?parseInt(a[1])/100+"":""},Na={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,c){"important"!=c?this.setAttribute(a,b):(c=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"),a=";"+a+":"+b+" !important;",this.cssText=c.test(this.cssText)?this.cssText.replace(c,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||"").match(RegExp(a+
"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"))||[])[2]||""},item:Y()},V={"for":"htmlFor","class":"className",value:"defaultValue"},ja={action:p,cite:p,codebase:p,data:p,href:p,longdesc:p,lowsrc:p,src:p,usemap:p,disabled:p},T={id:p,value:p,checked:p,ismap:p,multiple:p,readonly:p,selected:p},W={style:{get:function(){return this.style&&this.style.cssText?this.style.cssText:p},set:function(a){this.style&&(this.style.cssText=a);return a},remove:function(){return this.style&&this.style.cssText?
(this.style.cssText="",n):q},has:function(){return!(!this.style||!this.style.cssText)}}},H,X,L,O="uuid"+(Math.random()+"").substr(2),rb=1,sb=Y(),Ua=q,Oa,$="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|main|nav|output|progress|section|source|summary|time|video",oa=$.split("|"),Da=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,
za,I,aa,Pa,da,ea;"CSS1Compat"===g.compatMode?(da=function(){return r.scrollLeft},ea=function(){return r.scrollTop}):(da=function(){return g.body.scrollTop},ea=function(){return g.body.scrollLeft});g.head||(g.head=g.getElementsByTagName("head")[0]);"defaultView"in g||(g.defaultView=g.parentWindow);d=q;try{d=isNaN.apply(p,{})}catch(wb){}d||(Function.prototype.apply=function(a,b){var c;if(!b||!(c=+b.length))return s.call(this,a);if("object"!==typeof b||0>c||"callee"in b&&"caller"in b||"[object Array]"==
va.call(b))return la.call(this,a,b);switch(c){case 1:return s.call(this,a,b[0]);case 2:return s.call(this,a,b[0],b[1]);case 3:return s.call(this,a,b[0],b[1],b[2]);case 4:return s.call(this,a,b[0],b[1],b[2],b[3]);case 5:return s.call(this,a,b[0],b[1],b[2],b[3],b[4]);case 6:return s.call(this,a,b[0],b[1],b[2],b[3],b[4],b[5]);case 7:return s.call(this,a,b[0],b[1],b[2],b[3],b[4],b[5],b[6])}return la.call(this,a,nb(b))});"b"!=="ab".substr(-1)&&(String.prototype.substr=function(a,b){return lb.call(this,
0>a?0>(a=this.length+a)?0:a:a,b)});if(2!=="ab".split(/(?:ab)*/).length||4!==".".split(/(.?)(.?)/).length||"t"==="tesst".split(/(s)*/)[1]||0==="".split(/.?/).length||1<".".split(/()()/).length)ya=/()??/.exec("")[1]===k,String.prototype.split=function(a,b){var c=this;if(!(a instanceof RegExp))return a===k&&0===b?[]:ma.call(c,a,b);var e=[],h=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.extended?"x":"")+(a.sticky?"y":""),f=0,g,d,j;a=RegExp(a.source,h+"g");c+="";ya||(g=RegExp("^"+a.source+"$(?!\\s)",
h));b=b===k?4294967295:b>>>0;if(!b)return[];for(;d=a.exec(c);){h=d.index+d[0].length;if(h>f&&(e.push(c.slice(f,d.index)),!ya&&1<d.length&&d[0].replace(g,function(){for(var a=1,b=arguments.length-2;a<b;a++)arguments[a]===k&&(d[a]=k)}),1<d.length&&d.index<c.length&&e.push.apply(e,d.slice(1)),j=d[0].length,f=h,e.length>=b))break;a.lastIndex===d.index&&a.lastIndex++}f===c.length?(j||!a.test(""))&&e.push(""):e.push(c.slice(f));return e.length>b?e.slice(0,b):e};f.DOMException||(d=(f.DOMException=Y()).prototype=
Error(),d.INDEX_SIZE_ERR=1,d.HIERARCHY_REQUEST_ERR=3,d.WRONG_DOCUMENT_ERR=4,d.INVALID_CHARACTER_ERR=5,d.NO_MODIFICATION_ALLOWED_ERR=7,d.NOT_FOUND_ERR=8,d.NOT_SUPPORTED_ERR=9,d.INVALID_STATE_ERR=11,d.SYNTAX_ERR=12,d.INVALID_MODIFICATION_ERR=13,d.NAMESPACE_ERR=14,d.INVALID_ACCESS_ERR=15);"pageXOffset"in f||B.push(function(){Object.defineProperty(f,"pageXOffset",{get:da});Object.defineProperty(f,"pageYOffset",{get:ea})});K=f.Event=function(){Z("")};X={initEvent:function(a,b,c){(a==k||b==k||c==k)&&Z("WRONG_ARGUMENTS_ERR");
this.type=a;this.bubbles=b;this.cancelable=c;this.h=q;this.target=p;this.timeStamp||(this.timeStamp=+new Ca)},initCustomEvent:function(a,b,c,e){X.initEvent.call(this,a,b,c);this.detail=e},initUIEvent:function(a,b,c,e,h){X.initCustomEvent.call(this,a,b,c,h);this.view=e},initMouseEvent:function(a,b,c,e,h,f,d,g,j,m,r,l,z,s,u){X.initUIEvent.call(this,a,b,c,e,h);this.screenX=f;this.screenY=d;this.clientX=g;this.clientY=j;this.ctrlKey=m;this.altKey=r;this.shiftKey=l;this.metaKey=z;this.button=s;this.relatedTarget=
u}};L=K.prototype={constructor:K,preventDefault:function(){this.cancelable!==q&&(H.a.call(this).returnValue=this.returnValue=q,H.d.call(this),this.defaultPrevented=n)},stopPropagation:function(){H.a.call(this).cancelBubble=this.cancelBubble=n;H.d.call(this)}};L.stopImmediatePropagation=function(){this.__stopNow=n;this.stopPropagation()};L.defaultPrevented=q;for(d in X)ga(X,d)&&(L[d]=function(){X[arguments.callee.name].apply(this,arguments);La(this.ietl9_event,this)},L[d].name=d);H=function(a){this.ietl9_event=
a;a.returnValue=n;La(this,a)};H.a=function(){var a=this.ietl9_event;a===k?Z("WRONG_THIS_ERR"):a===p&&(a=H.a.k);return a};H.a.k={};H.d=function(){this.ietl9_event&&(this.ietl9_event=p)};K=Y();K.prototype=L;K=new K;K.constructor=H;H.prototype=K;w.addEventListener||((f.Text&&f.Text.prototype||j).addEventListener=j.addEventListener=r.addEventListener=f.addEventListener=g.addEventListener=function(a,b,c){if("function"===typeof b||"object"===typeof b){var e=this,h=e._,d=q;e==f&&(!("_"in g)||!("_e_8vj"in
g._)||!(a in g._._e_8vj))&&g.addEventListener(a,sb,c);h||(h=e._={});switch(a){case "DOMContentLoaded":if("complete"==g.readyState)return;e===f&&(e=g);d=n;if(!Oa){Oa=n;var j=function(){try{r.doScroll("left")}catch(b){setTimeout(j,50);return}J.call(e,{type:a,isTrusted:n,__custom_event:k})};if("createEventObject"in g&&"doScroll"in r)try{f.frameElement||j()}catch(x){}}break;case "load":"tagName"in e&&-1!="SCRIPT|IFRAME".indexOf(e.tagName.toUpperCase())&&(d=n,e.onreadystatechange=function(){"loaded"===
e.readyState&&(e.onreadystatechange=p,e.attachEvent("onreadystatechange",F.call(J,e,{type:a})))},a="readystatechange");break;case "DOMMouseScroll":a="mousewheel"}e.setInterval&&(e!=f&&!e.frameElement)&&(e=f);b[O]||(b[O]=++rb);if(!(c=h._h_9e2))c=h._h_9e2=F.call(J,e);h._e_8vj||(h._e_8vj={});a in h._e_8vj?h=h._e_8vj[a]:(h=h._e_8vj[a]=[],d||e.attachEvent("on"+a,c));"_"+b[O]in h||(h.push(b),h["_"+b[O]]=p)}},j.addEventListener.__shim__=n,(f.Text&&f.Text.prototype||j).removeEventListener=j.removeEventListener=
r.removeEventListener=f.removeEventListener=g.removeEventListener=function(a,b){var c=this._,e,h,d,f,g;if(!("function"!==typeof b&&!("object"===typeof b&&b.handleEvent)||!b[O]||!c))if(e=c._h_9e2){h=c._e_8vj&&c._e_8vj[a];for(f=0;g=h[f++];)if(g===b){mb.call(h,f-1,1);delete h["_"+b[O]];break}if(!h.length){this.detachEvent("on"+a,e);delete c._e_8vj[a];for(d in c._e_8vj)if(ga(c._e_8vj,d))return;delete c._e_8vj;delete c._h_9e2}}},j.removeEventListener.__shim__=n,g.attachEvent("onmousedown",function(){G.b=
event.button}),g.attachEvent("onclick",function(){G.b=k}));w.dispatchEvent||((f.Text&&f.Text.prototype||j).dispatchEvent=j.dispatchEvent=r.dispatchEvent=f.dispatchEvent=g.dispatchEvent=function(a){if(!a.type)return n;a.returnValue||(a.returnValue=n);a.cancelBubble&&(a.cancelBubble=q);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===f||-2146827850===b.number&&!(a.bubbles=q)){a.__custom_event=n;for(var c=a.target=this,e="on"+a.type;!a.cancelBubble&&
c;)(e in c&&"function"==typeof c[e]&&(a.__dom0__=c[e])||"_"in c&&"_e_8vj"in c._)&&J.call(c,a),c=a.bubbles?c===g?g.defaultView:c.parentNode:p,"__dom0__"in a&&(a.__dom0__=k,delete a.__dom0__);return!a.cancelBubble}Z(b)}},j.dispatchEvent.__shim__=n);g.createEvent||(g.createEvent=function(){return new H(g.createEventObject())});B.push(function(){function a(a){var b,c=this.nodeName.toUpperCase(),e,d,f,j,l,m,r,s;if(!("INPUT"!=c&&"TEXTAREA"!=c)){"unknown"!=typeof g.activeElement&&(m=g.activeElement);b=g.selection;
this._&&(r=this._.__stop_events__,this._.__stop_events__=n);m&&m._&&(s=m._.__stop_events__,m._.__stop_events__=n);try{this.focus(),e=b.createRange(),d=e.duplicate(),"TEXTAREA"==c?(f=this.value,e=d,a?(e.moveEnd("character",f.length),l=""==e.text?f.length:f.lastIndexOf(e.text)):(e.moveStart("character",-f.length),l=e.text.length)):(d.moveToElementText(this),d.setEndPoint("EndToEnd",e),j=d.text.length-e.text.length,l=a?j:j+e.text.length),m&&m.focus&&m.focus()}catch(u){l=k}this._&&!r&&delete this._.__stop_events__;
m&&(m._&&!s)&&delete m._.__stop_events__;return l}}function b(a,b){if(a!=k){b==k&&(b=a);var c=this.nodeName.toUpperCase();"INPUT"!=c&&"TEXTAREA"!=c||(c=this.createTextRange(),c.collapse(n),c.moveStart("character",a),c.moveEnd("character",b),c.select())}}var c=f.HTMLTextAreaElement&&f.HTMLTextAreaElement.prototype,e={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,n)},set:function(c){b.call(this,c,a.call(this));return c}},selectionEnd:{get:function(){return a.call(this)},
set:function(c){b.call(this,a.call(this,n),c);return c}}};Object.defineProperties(f.HTMLInputElement&&f.HTMLInputElement.prototype||m,e);c&&Object.defineProperties(c,e)});8>S&&(m.ielt8=n);g.doctype===p&&7<S&&B.push(function(){var a=g.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});Object.defineProperty(g,"doctype",{configurable:n,enumerable:q,get:function(){return a}})});j.contains||(j.contains=ob);s.call(xa,g,"").contains||(f.Text&&f.Text.prototype?B.push(F.call(D,p,
Text.prototype,j)):function(){var a;try{a=s.call(xa,this,"a"),a.contains=Y()}catch(b){return q}return n}()&&(g.createTextNode=function(a){a=s.call(xa,this,a);a.contains=j.contains;return a}));!s.call(wa,g).contains&&(f.HTMLDocument&&f.HTMLDocument.prototype)&&B.push(F.call(D,p,f.HTMLDocument.prototype,j));"children"in w||B.push(function(){Object.defineProperty(m,"children",{get:function(){for(var a=[],b=this.firstChild;b;)1==b.nodeType&&a.push(b),b=b.nextSibling;return a}})});B.push(function(){function a(a,
c){var e;try{a:{var h=a;"element"in h&&("defaults"in h&&"document"in h)&&(h=h.element);var d=h.getBoundingClientRect(),f,j,m;if((m=h.ownerDocument)!==g){if(f=m&&m.body,j=m&&m.documentElement,!f||!j){e=c?d.left:d.top;break a}}else f=g.body,j=r;e=c?d.left+da()-(j.clientLeft||f.clientLeft||0):d.top+ea()-(j.clientTop||f.clientTop||0)}}catch(s){e=a;h=0;for(d=c?"offsetLeft":"offsetTop";e;)h+=parseInt(e[d],10),e=e.offsetParent;e=h}return e}Object.defineProperties(m,{offsetLeft:{get:function(){return a(this,
n)}},offsetTop:{get:function(){return a(this)}}})});w.childElementCount==k&&B.push(function(){Object.defineProperties(m,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;return a}},nextElementSibling:{get:function(){for(var a=this;(a=a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=this;(a=a.previousSibling)&&
1!=a.nodeType;);return a}}})});g.ELEMENT_NODE||(d={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},D(g,d),D(j,d),D(f.Node,d));"textContent"in w||B.push(function(){Object.defineProperty(j,"textContent",{get:function(){if("innerText"in this)return this.innerText;if("data"in this&&this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in this&&this.replaceData&&this.replaceData(0,
this.length,a);return a}})});"isEqualNode"in w||(g.isEqualNode=r.isEqualNode=j.isEqualNode=function(a){var b,c;if(a===p||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return q;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=a.prefix||this.localName!=a.localName)return q;b=0;for(c=this.attributes.length;b<c;b++){var e=this.attributes[length],d=a.getAttributeNS(e.namespaceURI,e.localName);if(d===p||d.value!==
e.value)return q}}if(7===a.nodeType&&(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return q;b=0;for(c=a.childNodes.length;b<c;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===q)return q;return n});g.importNode||(g.importNode=function(a,b){switch(a.nodeType){case 1:var c=g.createElement(a.nodeName),e=a.attributes,d,f,j;if(e&&0<e.length){f=0;for(j=e.length;f<j;)e=a.attributes[f++],c.setAttribute(e.nodeName,
a.getAttribute(e.nodeName))}if(b&&(d=a.childNodes)&&0<d.length){f=0;for(j=d.length;f<j;)c.appendChild(g.importNode(d[f++],b))}return c;case 3:case 4:case 8:return g.createTextNode(a.nodeValue)}Ka("NOT_SUPPORTED_ERR");return p},g.importNode.shim=n);d="compareDocumentPosition";if(!(d in g)){var u,y=u||"DOCUMENT_POSITION_";r[d]=g[d]=j[d]=function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&
4)+(this.sourceIndex>a.sourceIndex&&2):1)+0:0};u="DISCONNECTED";r[y+u]=g[y+u]=j[y+u]=1;u="PRECEDING";r[y+u]=g[y+u]=j[y+u]=2;u="FOLLOWING";r[y+u]=g[y+u]=j[y+u]=4;u="CONTAINS";r[y+u]=g[y+u]=j[y+u]=8;u="CONTAINED_BY";r[y+u]=g[y+u]=j[y+u]=16}f.getComputedStyle||(f.getComputedStyle=function(a){var b=a.currentStyle||a.runtimeStyle;"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=F.call(Na.getPropertyValue,a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=f.getComputedStyle.j,a.runtimeStyle.getPropertyPriority=
f.getComputedStyle.i,a.runtimeStyle.item=Na.item);var c,e,d;(e=f.CSSStyleDeclaration)&&(e=e.prototype)&&(!("float"in b)||!("opacity"in b))?("float"in b||((c=Object.getOwnPropertyDescriptor(e,"float"))&&delete e["float"],d=F.call(f.getComputedStyle.e,a),Object.defineProperty(a.runtimeStyle,"float",{value:{valueOf:d,toString:d},configurable:n,writable:n}),c&&Object.defineProperty(e,"float",c)),"opacity"in b||((c=Object.getOwnPropertyDescriptor(e,"opacity"))&&"opacity"in e&&delete e.opacity,d=F.call(f.getComputedStyle.f,
a),Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:d,toString:d},configurable:n,writable:n}),c&&Object.defineProperty(e,"opacity",c))):("float"in b||(d=F.call(f.getComputedStyle.e,a),a.runtimeStyle["float"]={valueOf:d,toString:d}),"opacity"in b||(d=F.call(f.getComputedStyle.f,a),a.runtimeStyle.opacity={valueOf:d,toString:d}));return a.currentStyle},f.getComputedStyle.f=function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||Ma.call(this.style)||Ma.call(this.runtimeStyle)},
f.getComputedStyle.e=function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},f.getComputedStyle.j=function(){Ka("NO_MODIFICATION_ALLOWED_ERR")},f.getComputedStyle.i=function(){return""});g.createDocumentFragment=function(){var a=s.call(wa,this);f.DocumentFragment===f.Document&&D(a,f.DocumentFragment.prototype);return pa(a)};za=(w.innerHTML="<x-x></x-x>",1===w.childNodes.length&&1===w.childNodes[0].nodeType);$="|"+$+"|";na.ielt9=n;I=pa(s.call(wa,g));za||(pa(g),g.head.insertAdjacentHTML("beforeend",
"<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section,main{display:block}mark{background:#FF0;color:#000}</style>"));0===s.call(ia,g,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(aa=I.appendChild("createElement"in I&&I.createElement("div")||I.ownerDocument.createElement("div")),Pa=8===S?w.cloneNode:8>S?j.cloneNode:k,j.cloneNode=function(a){var b,c;Da.test(this.nodeName)?b=s.call(this.__nativeCloneNode__||Pa,this,a):(aa.innerHTML="",c=a?this.outerHTML:this.outerHTML.replace(/<(\w+)([^>]*)>[\W\w]*$/,
"<$1$2></$1>"),aa.innerHTML=c.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=aa.firstChild,!b&&!a&&((c=c.match(pb))&&(c=c[1]),c&&(I.createElement(c),aa.innerHTML=c,b=aa.firstChild)));return I.appendChild(b)});w=d=K=nodeList_methods_fromArray=za=p;if(j.ie||!(7<S)){var tb=Array.prototype.unshift,ua=!document.readyState,ba=["/a.ielt8.htc"],ca="{behavior:",Qa=[],Ra,Sa,Ta,Q,ub=f.scrollTo,vb=f.scrollBy,bb={checked:p,disabled:p,ismap:p,multiple:p,readonly:p,selected:p};for(d=ba.length;0<=--d;)ca+=
' url("'+ba[d]+'")';ca+="}";ua&&(g.readyState="uninitialized");j.ielt8=n;f.__ielt8__wontfix=Qa;var qa=/\s*(\S+)\s*/g,ra="(?=(^|.*\\s)$1(\\s|$))",hb=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,db=/\s*([,>+~ ])\s*/g,eb=/\~\=/g,gb=/(^[>+~ ]?|,|\>|\+|~| ).*?(?=[,>+~ ]|$)/g,Fa=/\./g,cb=/\s/g,Va=/^([,>+~ ])?([\|\*\w-]*)\#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?:\:(.+))?$/,Xa=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$\@!]?=)['"]?(.*?)['"]?)?\]?$/,Za=/^([^(]+)(?:\((.+)\))?$/,fb=/\-child\((\dn)\+(\d)\)/g,ab=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,
ib=/([,>+~ ])/,Wa={"":1," ":1,",":1,">":2,"~":3,"+":4},Ya={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},$a={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16},Ha=function(a){for(var b=a.length>>>0,c=[],e=0;e<b;e++)e in a&&c.push(a[e]);return c},sa=function(a){for(;(a=a.nextSibling)&&1!=a.nodeType;);return a};d="matchesSelector";
r[d]||(m[d]=r[d]=ka);d="matches";r[d]||(m[d]=r[d]=ka);d="querySelectorAll";g[d]||(m[d]=r[d]=g[d]=function(a,b){return ta.call(this,a,q,b)});d="querySelector";g[d]||(m[d]=r[d]=g[d]=function(a,b){return ta.call(this,a,n,b)[0]||p});d="getElementsByClassName";g[d]||(m[d]=r[d]=g[d]=function(a){a=RegExp(a.replace(qa,ra));for(var b=this.all,c,e=-1,d=[];c=b[++e];)c.className&&a.test(c.className)&&d.push(c);return d});T.g={};T.c=function(a,b){if(b in this)return n;var c=a.nodeName;if(!(a=T.g[c]))a=T.g[c]=
ia(c);return this[b]=a.getAttribute(b)!==p};m.setAttribute=function(a,b,c){if(c==k){var e=a.toLowerCase();c=1;if(e in W)return W[e].set.call(this,b);V[e]!==k?a=V[e]:ja[e]!==k?c=2:-1===e.indexOf("-")&&!T.c(this,e)&&(a=a.toUpperCase());b+=""}return s.call(this.__setAttribute__,this,a,b,c)};m.getAttribute=function(a,b){var c;c=a.toLowerCase();var e,d;if(d=b==k)b=1;if((e=W[c])!==k)return e.get.call(this);if(ja[c]!==k)return s.call(this.__getAttribute__,this,a,2);c=V[c]!==k?V[c]:-1===c.indexOf("-")&&!T.c(this,
c)?a.toUpperCase():a;e=s.call(this.__getAttribute__,this,c,b);e!==p?d&&(e+=""):!(c in this)&&"string"===typeof this[a]?(e=this[c]=this[a],this.__removeAttribute__(a),e+=""):e=p;return e};m.removeAttribute=function(a,b){var c,d;if(b==k){b=1;d=a.toLowerCase();if(d in W)return W[d].remove.call(this);V[d]!==k?c=V[d]:ja[d]!==k?b=2:-1===d.indexOf("-")&&!T.c(this,d)&&(c=a.toUpperCase())}return s.call(this.__removeAttribute__,this,c||a,b)};j.hasAttribute||(j.hasAttribute=function(a){var b=(a+"").toLowerCase();
return b in W?W[b].has.call(this):this.getAttribute(a)!==p});var M=function(a){return function(){return a}};j.l=M(1);j.p=M(2);j.q=M(3);j.r=M(4);j.s=M(7);j.t=M(8);j.u=M(9);j.m=M(10);j.n=M(11);j.o=M(16);j.__ielt8__element_init__=function(){var a=this;a.element&&(a=a.element);"prepend"in a||(a.after=m.after,a.before=m.before,a.append=m.append,a.prepend=m.prepend,a.replace=m.replace,a.remove=m.remove);"isEqualNode"in a||(a.isEqualNode=j.isEqualNode);"compareDocumentPosition"in a||(a.compareDocumentPosition=
j.compareDocumentPosition);"getElementsByClassName"in a||(a.getElementsByClassName=m.getElementsByClassName);"addEventListener"in a||(a.addEventListener=f.addEventListener,a.removeEventListener=f.removeEventListener,a.dispatchEvent=f.dispatchEvent);"querySelector"in a||(a.querySelectorAll=m.querySelectorAll,a.querySelector=m.querySelector);"matchesSelector"in a||(a.matchesSelector=a.matches=ka);"hasAttribute"in a||(a.hasAttribute=m.hasAttribute);"setSelectionRange"in a||(a.setSelectionRange=m.setSelectionRange);
try{this.setAttribute!=m.setAttribute&&(this.__setAttribute__=this.setAttribute,this.__getAttribute__=this.getAttribute,this.__removeAttribute__=this.removeAttribute,this.setAttribute=m.setAttribute,this.getAttribute=m.getAttribute,this.removeAttribute=m.removeAttribute),a.cloneNode!==j.cloneNode&&(a.__nativeCloneNode__=a.cloneNode,a.cloneNode=j.cloneNode),j.contains&&(a.contains=j.contains)}catch(b){Qa.push(a)}};Ta=j.__ielt8_Node_behavior_apply=function(a){for(d=ba.length;0<=--d;)try{a.addBehavior(ba[d])}catch(b){}};
Sa=j.cloneNode;j.cloneNode=function(a){a=s.call(Sa||this.__nativeCloneNode__,this,a);Ta(a);return a};1!=[].unshift(0)&&(Array.prototype.unshift=function(){tb.apply(this,arguments);return this.length});Ra=g.createElement;g.createElement=function(a){a=s.call(Ra,g,a);for(var b=ba.length;0<=--b;)try{a.addBehavior(ba[b])}catch(c){}return a};f.XMLHttpRequest||(f.XMLHttpRequest=function(){var a;try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){a=new ActiveXObject("Microsoft.XMLHTTP")}var c=a.send;a.send=
function(){this.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");c.apply(this,arguments)}});!("pageXOffset"in f)&&f.attachEvent&&(f.pageXOffset=f.pageYOffset=0,Q="CSS1Compat"===g.compatMode?function(){f.scrollX=f.pageXOffset=g.body.parentNode.scrollLeft;f.scrollY=f.pageYOffset=g.body.parentNode.scrollTop}:function(){f.scrollX=f.pageXOffset=g.body.scrollLeft;f.scrollY=f.pageYOffset=g.body.scrollTop},f.attachEvent("onscroll",Q),f.scroll=f.scrollTo=function(a,b){ub(a,b);Q()},f.scrollBy=
function(a,b){vb(a,b);Q()});g.addEventListener("DOMContentLoaded",Ia);f.attachEvent("onload",Ja);var Aa=ca,C=g.getElementById("ielt8_style_prev_for_behaviour"),Ba="";C&&(Ba=C.getAttribute("data-url")||"",C.id="");Ba&&Aa.replace(" url("," url("+Ba+") url(");C=ia("style");C.id="ielt8_style_prev_for_behaviour";C.type="text/css";C.setAttribute("data-url",Aa.replace("{behavior:","").replace(")}",")"));C.styleSheet.cssText="*"+Aa;g.head.appendChild(C);ca=d=p}}}.call(window,function(D,G){for(var J in G)Object.prototype.hasOwnProperty.call(G,
J)&&!Object.prototype.hasOwnProperty.call(D,J)&&(D[J]=G[J]);return D});
