/* ES6/DOM4 polyfill for IE8 | @version 0.7 final | MIT License | github.com/termi */
;(function() {
var j=void 0,k=!0,m=null,q=!1;function K(){return function(){}}
(function(d,u){function v(a){if(!("__isFixed"in a)){var b="button"in a&&a.button;a.__isFixed=k;if("click"===a.type||"dblclick"===a.type)a.detail===j&&(a.detail="click"===a.type?1:2),!a.button&&v.b!==j&&(b=v.b);u(a,A);a.defaultPrevented||(a.defaultPrevented=q);a.target||(a.target=a.srcElement||document);a.relatedTarget===j&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==m&&(a.pageX=a.clientX+L()-(n.clientLeft||0),a.pageY=a.clientY+M()-(n.clientTop||
0));!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new aa);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);"currentTarget"in a||(a.currentTarget=this);!a.attrName&&a.propertyName&&(a.attrName=ba.call(a.propertyName,".")[0]);return a}}function N(a){if(v!==j){var b=this._,c,f,h,d;if(!b.__stop_events__){c=[];f=[];d="_e_8vj"+(ka?"-":"");if(!b||!b[d])if("__dom0__"in a)b||(b={}),b[d]||(b[d]={});else return;a||(a=window.event);if("__custom_event"in a)h=a;else if(!(h=a.__customEvent__))a.bubbles==
j&&(a.bubbles=k),a.cancelable==j&&(a.cancelable=k),h=a.__customEvent__=new t(a),h.initEvent(a.type,a.bubbles,a.cancelable),v.call(this,h),h.g=k,h.__custom_event=j;h.ietl9_event=a;a.currentTarget=this;b=b[d][h.type];"__dom0__"in a&&((b||(b=[]))[0]=a.__dom0__);if(b){for(var e in b)if(B(b,e)){d=b[e];var g;"object"===typeof d&&(g=d,d=d.handleEvent);try{if(d&&(h.result=y.call(d,g||this,h))===q)h.preventDefault(),h.stopPropagation()}catch(r){c.push(r),f.push(r.message),console&&console.error(r)}if(h.__stopNow)break}b[0]=
j;delete b[0];a.returnValue=h.returnValue;a.cancelBubble=h.cancelBubble;1==c.length?C(c[0]):1<c.length&&(f=Error("Multiple errors thrown : "+h.type+" :  : "+f.join("|")),f.h=c,C(f))}this===document&&(!h.cancelBubble&&3===h.eventPhase)&&(N.call(this.defaultView,h),a.cancelBubble=k)}}}function D(){}function la(){var a=document.querySelectorAll("#z").constructor.prototype;if(a&&a!==Array.prototype)for(var b in Q)B(b,Q)&&(a[b]||(a[b]=function(){return O.call(Array.prototype[b],Array.from(this),arguments)}))}
function R(a){var b=this.__orig__createElement__(a);if(ca.test(a))return b;~G.indexOf("|"+a+"|")||(S.push(a),G+=a+"|",(w.__orig__createElement__||w.createElement)(a));return w.appendChild(b)}function T(a){var b=-1;if(a.createElement){for(;++b<S.length;)a.createElement(S[b]);a.createElement!==R&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=R)}return a}var P=window.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||j;if(9>
P){d.Element||((d.Element=ActiveXObject).prototype.ie=k);d.HTMLElement||(d.HTMLElement=d.Element);d.Node||(d.Node=d.Element);var s;d.DocumentFragment||(d.DocumentFragment=d.Document||d.HTMLDocument||(s=K(),s.prototype={},s));d.Document||(d.Document=d.DocumentFragment);d._={ielt9shims:[],orig_:d._};var g=d._.ielt9shims,U=document.createDocumentFragment,da=document.createElement,ea=document.createTextNode,n=document.documentElement,C=function(a){throw a instanceof Error?a:Error(a);},fa=function(a){var b=
Object.create(DOMException.prototype);b.code=DOMException[a];b.message=a+": DOM Exception "+b.code;throw b;},ga=function(a,b){for(var c in b)if(B(b,c)&&a[c]!==b[c])try{a[c]=b[c]}catch(f){}},oa=String.prototype.trim||function(){for(var a=this.replace(ma,""),b=a.length;na.test(a.charAt(--b)););return a.slice(0,b+1)},ba=String.prototype.split,pa=String.prototype.substr,ha=Array.prototype.slice,O=Function.prototype.apply,y=Function.prototype.call,z=Function.prototype.bind||function(a,b){var c=this,f=
ha.call(arguments,1);return function(){return O.call(c,a,f.concat(ha.call(arguments)))}},B=z.call(Function.prototype.call,Object.prototype.hasOwnProperty);s=document.createElement("p");var l=d.Node.prototype,p=d.Element.prototype,qa=s.contains||l.contains,aa=Date,ra=/^\<([\w\:\-]*)[\>\ ]/i,ma=/^\s+/,na=/\s/,V,e,x,Q="every filter forEach indexOf join lastIndexOf map reduce reduceRight reverse slice some toString".split(" "),W=/alpha\(opacity=([^\)]+)\)/,H=function(){var a=(this.filter||"").match(W);
return a?parseInt(a[1])/100+"":""},X={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,c){"important"!=c?this.setAttribute(a,b):(c=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"),a=";"+a+":"+b+" !important;",this.cssText=c.test(this.cssText)?this.cssText.replace(c,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||"").match(RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))",
"i"))||[])[2]||""},item:K()},I={"for":"htmlFor","class":"className",value:"defaultValue"},Y={action:m,cite:m,codebase:m,data:m,href:m,longdesc:m,lowsrc:m,src:m,usemap:m},E={id:k,value:k,checked:k,disabled:k,ismap:k,multiple:k,readonly:k,selected:k},t,F,A,sa=1,ta=K(),ka=q,ia,G="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|nav|output|progress|section|source|summary|time|video",S=G.split("|"),ca=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,
i,w,J,ja,L,M;"CSS1Compat"===document.compatMode?(L=function(){return n.scrollLeft},M=function(){return n.scrollTop}):(L=function(){return document.body.scrollTop},M=function(){return document.body.scrollLeft});document.head||(document.head=document.getElementsByTagName("head")[0]);"defaultView"in document||(document.defaultView=document.parentWindow);e=q;try{e=isNaN.apply(m,{})}catch(wa){}e||(Function.prototype.apply=function(a,b){try{return b!=j?O.call(this,a,b):O.call(this,a)}catch(c){return(-2146823260!=
c.number||b.length===j||"string"===typeof b)&&C(c),O.call(this,a,Array.from(b))}});"b"!=="ab".substr(-1)&&(String.prototype.substr=function(a,b){return pa.call(this,0>a?0>(a=this.length+a)?0:a:a,b)});if("te".split(/(s)*/)[1]!=j||3!="1_1".split(/(_)/).length)V=/()??/.exec("")[1]===j,String.prototype.split=function(a,b){var c=this;if(!(a instanceof RegExp))return a===j&&0===b?[]:ba.call(c,a,b);var f=[],h=0,d=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.i?"y":""),e=RegExp(a.source,d+"g"),g=m,r,i,c=
c+"";V||(g=RegExp("^"+e.source+"$(?!\\s)",d));if(b===j||0>+b)b=Infinity;else if(b=Math.floor(+b),!b)return[];for(;r=e.exec(c);){d=r.index+r[0].length;if(d>h&&(f.push(c.slice(h,r.index)),!V&&1<r.length&&r[0].replace(g,function(){for(var a=1,b=arguments,c=b.length-2;a<c;a++)b[a]===j&&(r[a]=j)}),1<r.length&&r.index<c.length&&f.push.apply(f,r.slice(1)),i=r[0].length,h=d,f.length>=b))break;e.lastIndex===r.index&&e.lastIndex++}h===c.length?(i||!e.test(""))&&f.push(""):f.push(c.slice(h));return f.length>
b?f.slice(0,b):f};d.DOMException||(e=(d.DOMException=K()).prototype=Error(),e.INDEX_SIZE_ERR=1,e.HIERARCHY_REQUEST_ERR=3,e.WRONG_DOCUMENT_ERR=4,e.INVALID_CHARACTER_ERR=5,e.NO_MODIFICATION_ALLOWED_ERR=7,e.NOT_FOUND_ERR=8,e.NOT_SUPPORTED_ERR=9,e.INVALID_STATE_ERR=11,e.SYNTAX_ERR=12,e.INVALID_MODIFICATION_ERR=13,e.NAMESPACE_ERR=14,e.INVALID_ACCESS_ERR=15,e.TYPE_MISMATCH_ERR=17);"pageXOffset"in d||g.push(function(){Object.defineProperty(d,"pageXOffset",{get:L});Object.defineProperty(d,"pageYOffset",{get:M})});
x=d.Event=function(){C("")};F={initEvent:function(a,b,c){(a==j||b==j||c==j)&&C("WRONG_ARGUMENTS_ERR");this.type=a;this.bubbles=b;this.cancelable=c;this.g=q;this.target=m;this.timeStamp||(this.timeStamp=+new aa)},initCustomEvent:function(a,b,c,f){F.initEvent.call(this,a,b,c);this.detail=f},initUIEvent:function(a,b,c,f,h){F.initCustomEvent.call(this,a,b,c,h);this.view=f},initMouseEvent:function(a,b,c,f,h,d,e,g,r,i,l,n,p,s,t){F.initUIEvent.call(this,a,b,c,f,h);this.screenX=d;this.screenY=e;this.clientX=
g;this.clientY=r;this.ctrlKey=i;this.altKey=l;this.shiftKey=n;this.metaKey=p;this.button=s;this.relatedTarget=t}};A=x.prototype={constructor:x,preventDefault:function(){this.cancelable!==q&&(t.a.call(this).returnValue=this.returnValue=q,t.d.call(this),this.defaultPrevented=k)},stopPropagation:function(){t.a.call(this).cancelBubble=this.cancelBubble=k;t.d.call(this)}};A.stopImmediatePropagation=function(){this.__stopNow=k;this.stopPropagation()};A.defaultPrevented=q;for(e in F)B(F,e)&&(A[e]=function(){F[arguments.callee.name].apply(this,
arguments);ga(this.ietl9_event,this)},A[e].name=e);t=function(a){this.ietl9_event=a;a.returnValue=k;ga(this,a)};t.a=function(){var a=this.ietl9_event;a===j?C("WRONG_THIS_ERR"):a===m&&(a=t.a.f);return a};t.a.f={};t.d=function(){this.ietl9_event&&(this.ietl9_event=m)};x=K();x.prototype=A;x=new x;x.constructor=t;t.prototype=x;document.addEventListener||(l.addEventListener=n.addEventListener=d.addEventListener=document.addEventListener=function(a,b,c){if("function"==typeof b||"object"===typeof b&&b.handleEvent){var f=
this,h=f._,e=q;f==d&&(!("_"in document)||!("_e_8vj"in document._)||!(a in document._._e_8vj))&&document.addEventListener(a,ta,c);h||(h=f._={});switch(a){case "DOMContentLoaded":if("complete"==document.readyState)return;f===d&&(f=document);e=k;if(!ia){ia=k;var g=function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(g,50);return}N.call(f,{type:a,isTrusted:k,__custom_event:j})};if("createEventObject"in document&&"doScroll"in document.documentElement)try{d.frameElement||g()}catch(i){}}break;
case "load":"tagName"in f&&"SCRIPT"===f.tagName.toUpperCase()&&(e=k,f.onreadystatechange=function(){"loaded"===f.readyState&&(f.onreadystatechange=m,f.attachEvent("onreadystatechange",z.call(N,f,{type:a})))},a="readystatechange");break;case "DOMMouseScroll":a="mousewheel"}f.setInterval&&(f!=d&&!f.frameElement)&&(f=d);b.uuid||(b.uuid=++sa);if(!(c=h._h_9e2))c=h._h_9e2=z.call(N,f);h._e_8vj||(h._e_8vj={});h._e_8vj[a]||(h._e_8vj[a]={},e||f.attachEvent("on"+a,c));h._e_8vj[a][b.uuid]=b}},l.addEventListener.__shim__=
k,l.removeEventListener=n.removeEventListener=d.removeEventListener=document.removeEventListener=function(a,b){var c=this._,f,h,d;if(!("function"!=typeof b||!b.uuid||!c))if(f=c._h_9e2){h=c._e_8vj&&c._e_8vj[a];delete h[b.uuid];for(d in h)if(B(h,d))return;this.detachEvent("on"+a,f);delete c._e_8vj[a];for(d in c._e_8vj)if(B(c._e_8vj,d))return;delete c._e_8vj}},l.removeEventListener.__shim__=k,document.attachEvent("onmousedown",function(){v.b=event.button}),document.attachEvent("onclick",function(){v.b=
j}));document.dispatchEvent||(l.dispatchEvent=n.dispatchEvent=d.dispatchEvent=document.dispatchEvent=function(a){if(!a.type)return k;a.returnValue||(a.returnValue=k);a.cancelBubble&&(a.cancelBubble=q);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===d||-2146827850===b.number&&!(a.bubbles=q)){a.__custom_event=k;for(var c=a.target=this,f="on"+a.type;!a.cancelBubble&&c;)(f in c&&"function"==typeof c[f]&&(a.__dom0__=c[f])||"_"in c&&"_e_8vj"in c._)&&
N.call(c,a),c=a.bubbles?c===document?document.defaultView:c.parentNode:m,"__dom0__"in a&&(a.__dom0__=j);return!a.cancelBubble}C(b)}},l.dispatchEvent.__shim__=k);document.createEvent||(document.createEvent=function(){return new t(document.createEventObject())});g.push(function(){function a(a){var b,c=this.nodeName.toUpperCase(),f,d,e,g,i,l,n,p;if(!("INPUT"!=c&&"TEXTAREA"!=c)){l=document.activeElement;b=document.selection;this._&&(n=this._.__stop_events__,this._.__stop_events__=k);l._&&(p=l._.__stop_events__,
l._.__stop_events__=k);try{this.focus(),f=b.createRange(),d=f.duplicate(),"TEXTAREA"==c?(e=this.value,f=d,a?(f.moveEnd("character",e.length),i=""==f.text?e.length:e.lastIndexOf(f.text)):(f.moveStart("character",-e.length),i=f.text.length)):(d.moveToElementText(this),d.setEndPoint("EndToEnd",f),g=d.text.length-f.text.length,i=a?g:g+f.text.length),l&&l.focus&&l.focus()}catch(s){i=j}this._&&!n&&delete this._.__stop_events__;l._&&!p&&delete l._.__stop_events__;return i}}function b(a,b){if(a!=j){b==j&&
(b=a);var c=this.nodeName.toUpperCase();"INPUT"!=c&&"TEXTAREA"!=c||(c=this.createTextRange(),c.collapse(k),c.moveStart("character",a),c.moveEnd("character",b-a),c.select())}}var c=d.HTMLTextAreaElement&&d.HTMLTextAreaElement.prototype,f={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,k)},set:function(c){b.call(this,c,a.call(this));return c}},selectionEnd:{get:function(){return a.call(this)},set:function(c){b.call(this,a.call(this,k),c);return c}}};Object.defineProperties(d.HTMLInputElement&&
d.HTMLInputElement.prototype||p,f);c&&Object.defineProperties(c,f)});D.prototype=[];e=new D;e.push(1);e.length?d.NodeList=D:(e=document.createElement("iframe"),e.style.display="none",(document.body||n).appendChild(e),e.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),D=d.NodeList);D.prototype.item=function(a){return this[a]};document.querySelectorAll&&la();document.doctype===m&&7<P&&g.push(function(){var a=document.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});
Object.defineProperty(document,"doctype",{configurable:k,enumerable:q,get:function(){return a}})});l.contains||(l.contains=qa);y.call(ea,document,"").contains||(d.Text&&d.Text.prototype?g.push(z.call(u,m,Text.prototype,l)):document.createTextNode=function(a){a=y.call(ea,this,a);a.contains=l.contains;return a});!y.call(U,document).contains&&(d.HTMLDocument&&d.HTMLDocument.prototype)&&g.push(z.call(u,m,d.HTMLDocument.prototype,l));"children"in s||g.push(function(){Object.defineProperty(p,"children",
{get:function(){for(var a=[],b=this.firstChild;b;)1==b.nodeType&&a.push(b),b=b.nextSibling;return a}})});g.push(function(){function a(a,c){var f;try{var d=a;"element"in d&&("defaults"in d&&"document"in d)&&(d=d.element);var e=d.getBoundingClientRect(),g=document.body;f=!n.contains(d)?c?e.left:e.top:c?e.left+L()-(n.clientLeft||g.clientLeft||0):e.top+M()-(n.clientTop||g.clientTop||0)}catch(i){f=a;d=0;for(e=c?"offsetLeft":"offsetTop";f;)d+=parseInt(f[e],10),f=f.offsetParent;f=d}return f}Object.defineProperties(p,
{offsetLeft:{get:function(){return a(this,k)}},offsetTop:{get:function(){return a(this)}}})});s.childElementCount==j&&g.push(function(){Object.defineProperties(p,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;return a}},nextElementSibling:{get:function(){for(var a=this;(a=a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=
this;(a=a.previousSibling)&&1!=a.nodeType;);return a}}})});document.ELEMENT_NODE||(e={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},u(document,e),u(l,e),u(d.Node,e));"textContent"in s||g.push(function(){Object.defineProperty(l,"textContent",{get:function(){if("innerText"in this)return this.innerText;if("data"in this&&this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in
this&&this.replaceData&&this.replaceData(0,this.length,a);return a}})});"isEqualNode"in s||(document.isEqualNode=n.isEqualNode=l.isEqualNode=function(a){var b,c;if(a===m||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return q;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=a.prefix||this.localName!=a.localName)return q;b=0;for(c=this.attributes.length;b<c;b++){var d=this.attributes[length],e=a.getAttributeNS(d.namespaceURI,
d.localName);if(e===m||e.value!==d.value)return q}}if(7===a.nodeType&&(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return q;b=0;for(c=a.childNodes.length;b<c;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===q)return q;return k});document.importNode||(document.importNode=function(a,b){switch(a.nodeType){case 1:var c=document.createElement(a.nodeName),d=a.attributes,e,g,i;if(d&&0<d.length){g=
0;for(i=d.length;g<i;)d=a.attributes[g++],c.setAttribute(d.nodeName,a.getAttribute(d.nodeName))}if(b&&(e=a.childNodes)&&0<e.length){g=0;for(i=e.length;g<i;)c.appendChild(document.importNode(e[g++],b))}return c;case 3:case 4:case 8:return document.createTextNode(a.nodeValue)}fa("NOT_SUPPORTED_ERR");return m},document.importNode.shim=k);e="compareDocumentPosition";e in document||(g=i||"DOCUMENT_POSITION_",n[e]=document[e]=l[e]=function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=
a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&4)+(this.sourceIndex>a.sourceIndex&&2):1)+0:0},i="DISCONNECTED",n[g+i]=document[g+i]=l[g+i]=1,i="PRECEDING",n[g+i]=document[g+i]=l[g+i]=2,i="FOLLOWING",n[g+i]=document[g+i]=l[g+i]=4,i="CONTAINS",n[g+i]=document[g+i]=l[g+i]=8,i="CONTAINED_BY",n[g+i]=document[g+i]=l[g+i]=16);d.getComputedStyle||(d.getComputedStyle=function(a){var b=a.currentStyle||a.runtimeStyle;"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=
X.getPropertyValue.bind(a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=function(){fa("NO_MODIFICATION_ALLOWED_ERR")},a.runtimeStyle.getPropertyPriority=function(){return""},a.runtimeStyle.item=X.item);var c,f;(f=d.CSSStyleDeclaration)&&(f=f.prototype)&&(!("float"in b)||!("opacity"in b))?("float"in b||((c=Object.getOwnPropertyDescriptor(f,"float"))&&delete f["float"],Object.defineProperty(a.runtimeStyle,"float",{value:{valueOf:z.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},
a)}}),c&&Object.defineProperty(f,"float",c)),"opacity"in b||((c=Object.getOwnPropertyDescriptor(f,"opacity"))&&delete f.opacity,Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:z.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||H.call(this.style)||H.call(this.runtimeStyle)},a)}}),c&&Object.defineProperty(f,"opacity",c))):("float"in b||(a.runtimeStyle["float"]={valueOf:z.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},a)}),"opacity"in
b||(a.runtimeStyle.opacity={valueOf:z.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||H.call(this.style)||H.call(this.runtimeStyle)},a)}));return a.currentStyle});document.createDocumentFragment=function(){var a=y.call(U,this);d.DocumentFragment===d.Document&&u(a,d.DocumentFragment.prototype);return T(a)};i=(s.innerHTML="<x-x></x-x>",1===s.childNodes.length&&1===s.childNodes[0].nodeType);G="|"+G+"|";R.ielt9=k;w=T(y.call(U,document));i||(T(document),document.head.insertAdjacentHTML("beforeend",
"<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>"));0===y.call(da,document,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(J=w.appendChild("createElement"in w&&w.createElement("div")||w.ownerDocument.createElement("div")),ja=8===P?s.cloneNode:8>P?l.cloneNode:j,l.cloneNode=function(a){var b,c;ca.test(this.nodeName)?b=y.call(this.__nativeCloneNode__||ja,this,a):(J.innerHTML="",c=a?this.outerHTML:this.outerHTML.replace(this.innerHTML,
""),J.innerHTML=c.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=J.firstChild,!b&&!a&&((c=c.match(ra))&&(c=c[1]),c&&(w.createElement(c),J.innerHTML=c,b=J.firstChild)));return w.appendChild(b)});var ua=/\s+(?=\S)|^/g,Z=p.getAttribute,va=p.setAttribute,$=p.removeAttribute;E.e={};E.c=function(a,b){if(b in this)return this[b];var c=a.nodeName;if(!(a=E.e[c]))a=E.e[c]=da(c);c=Z.call(a,b)!==m;c||(c=(c=a.constructor)&&(c=c.prototype)&&(c=Object.getOwnPropertyDescriptor(c,b))&&/\[native\scode\]/.test(c.get+
""));return this[b]=c};p.setAttribute=function(a,b){var c=a.toLowerCase();I[c]!==j?a=I[c]:Y[c]===j&&(0!==c.indexOf("data-")&&!E.c(this,c))&&(a=a.toUpperCase());return va.call(this,a,b+"")};p.getAttribute=function(a){var b;b=a.toLowerCase();var c;if(I[b]!==j)return Z.call(this,I[b]);if(Y[b]!==j)return(c=this.attributes)&&(c=c[b])&&(c=c.nodeValue)&&c+""||m;if(0!==b.indexOf("data-")&&!E.c(this,b))b=a.toUpperCase();else return Z.call(this,a);c=this[b];c||(!(b in this)&&"string"===typeof this[a]?(c=this[b]=
this[a],delete this[a]):c=j);return c?c+"":m};p.removeAttribute=function(a){var b;b=a.toLowerCase();var c;if(I[b]!==j)return $.call(this,I[b]);if(Y[b]===j&&0!==b.indexOf("data-")&&!E.c(this,b))b=a.toUpperCase();else return $.call(this,a);if((c=b in this)||this.getAttribute(a)!==m)$.call(this,b),delete this[b];return c};e="getElementsByClassName";!p[e]&&document.querySelectorAll&&(p[e]=n[e]=document[e]=function(a){return!a||!(a=oa.call(a))?new D:y.call(this.querySelectorAll||document.querySelectorAll,
this,a.replace(ua,"."))});if(e=d.CSSStyleDeclaration)"opacity"in n.style||(Object.defineProperty(e.prototype,"opacity",{get:H,set:function(a){"object"==typeof a&&(a=a.valueOf());this.opacity!==H.call(this)&&delete this.opacity;a=a&&"alpha(opacity="+(0.9999<=a?"100":0>a?0:~~(100*a))+")"||"";this.filter=W.test(this.filter)?this.filter.replace(W,a):this.filter+(" "+a);this.msOpacity=this.opacity}}),Object.defineProperty(e.prototype,"msOpacity",{value:""})),"float"in n.style||Object.defineProperty(e.prototype,
"float",{get:function(){return this.styleFloat},set:function(a){return this.styleFloat=a}}),"getPropertyValue"in e||function(a){for(var b in a)B.call(a,b)&&(this[b]=a[b])}.call(e,X);(function(a,b,c,d){function e(a){for(var b=a.length>>>0,c=new D,d=0;d<b;d++)d in a&&c.push(a[d]);return c}document.querySelectorAll=function(){return e(a.apply(this,arguments))};document.querySelector=function(){return b.apply(this,arguments)};p.querySelectorAll=function(){return e(c.apply(this,arguments))};p.querySelector=
function(){return d.apply(this,arguments)}})(document.querySelectorAll,document.querySelector,p.querySelectorAll,p.querySelector);s=e=x=Q=i=j}})(window,function(d,u){for(var v in u)Object.prototype.hasOwnProperty.call(u,v)&&!Object.prototype.hasOwnProperty.call(d,v)&&(d[v]=u[v]);return d});
})();
