/* ES6/DOM4 polyfill for IE8 | @version 0.8.8 | MIT License | github.com/termi */
void function(z){var k=void 0,m=!0,p=null,q=!1;function K(){return function(){}}function A(a){if(!("__isFixed"in a||a.isTrusted===q)){var b="button"in a&&a.button;a.__isFixed=m;if("click"===a.type||"dblclick"===a.type)a.detail===k&&(a.detail="click"===a.type?1:2),!a.button&&A.b!==k&&(b=A.b);z(a,G);a.defaultPrevented||(a.defaultPrevented=q);a.target||(a.target=a.srcElement||g);a.relatedTarget===k&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==p&&(a.pageX=a.clientX+P()-(r.clientLeft||0),a.pageY=a.clientY+
Q()-(r.clientTop||0));!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new ha);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);a.keyCode||(a.keyCode=a.charCode||a.which);!a.attrName&&a.propertyName&&(a.attrName=ia.call(a.propertyName,".")[0]);return a}}function B(a){if(A!==k){var b=this._,c,d,h,e,E,w,j,n;if(!b.__stop_events__){c=[];d=[];e="_e_8vj"+(qa?"-":"");if(!b||!b[e])if("__dom0__"in a)b||(b={}),b[e]||(b[e]={});else return;a||(a=f.event);if("__custom_event"in a)h=
a;else if(!(h=a.__customEvent__))a.bubbles==k&&(a.bubbles=m),a.cancelable==k&&(a.cancelable=m),h=a.__customEvent__=new x(a),h.initEvent(a.type,a.bubbles,a.cancelable),h.h=a.h!==q,A.call(this,h),h.__custom_event=p;h.ietl9_event=a;h.currentTarget=this;"__dom0__"in a&&(w=a.__dom0__);if((b=b[e][h.type])||w)E=b?F.call(b):[],w&&E.unshift(w);if(E&&E.length){for(;w=E.shift();)if(w&&(!(n=w[H])||"_"+n in b)){"object"===typeof w&&(j=w,w=w.handleEvent);try{if(w&&(h.result=s.call(w,j||this,h))===q)h.defaultPrevented===
q&&h.returnValue!==q&&h.preventDefault(),h.stopPropagation()}catch(l){c.push(l),d.push(l.message)}if(h.__stopNow)break}a.returnValue=h.returnValue;a.cancelBubble=h.cancelBubble;1==c.length?L(c[0]):1<c.length&&(d=Error("Multiple errors thrown : "+h.type+" :  : "+d.join("|")),d.errors=c,L(d))}this===g&&(!h.cancelBubble&&3===h.eventPhase)&&(B.call(this.defaultView,h),a.cancelBubble=m);x.d.call(h);a.__customEvent__=p}}}function V(a){var b=(this.__orig__createElement__||W)(a);if(ja.test(a))return b;~M.indexOf("|"+
a+"|")||(X.push(a),M+=a+"|",(C.__orig__createElement__||C.createElement)(a));return C.appendChild(b)}function Y(a){var b=-1;if(a.createElement){for(;++b<X.length;)a.createElement(X[b]);a.createElement!==V&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=V)}return a}var f=this,g=f.document,e,v="attachEvent"in g&&"all"in g&&"uniqueID"in g.documentElement&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||p;if(v&&!(9<v)){f.Element||((f.Element=f.ActiveXObject).prototype.ie=
m);f.HTMLElement||(f.HTMLElement=f.Element);f.Node||(f.Node=f.Element);f.DocumentFragment||(f.DocumentFragment=f.Document||f.HTMLDocument||(e=K(),e.prototype={},e));f.Document||(f.Document=f.DocumentFragment);f._={ielt9shims:[],orig_:f._,isPlainObject:function(a){return a&&"[object Object]"===Z.call(a)&&("function"===typeof a.constructor&&"[object Function]"===Z.call(a.constructor)||a.__proto__===p)&&!R(a,"callee")},apply:Function.prototype.apply};var n=f._.ielt9shims,$=g.createDocumentFragment,W=
g.createElement,aa=g.createTextNode,r=g.documentElement,L=function(a){throw"object"==typeof a&&a instanceof Error?a:Error(a);},ka=function(a){var b=Object.create(DOMException.prototype);b.code=DOMException[a];b.message=a+": DOM Exception "+b.code;throw b;},la=function(a,b){for(var c in b)if(R(b,c)&&a[c]!==b[c])try{a[c]=b[c]}catch(d){}},ta=String.prototype.trim||function(){for(var a=this.replace(ra,""),b=a.length;sa.test(a.charAt(--b)););return a.slice(0,b+1)},ia=String.prototype.split,ua=String.prototype.substr,
F=Array.prototype.slice,ba=Array.prototype.splice,va=function(a){var b,c=a.length>>>0,d;try{if(b=F.call(a),b.length===c)return b}catch(h){}b=[];for(d=0;d<c;d++)d in a&&(b[d]=a[d]);return b},T=Function.prototype.apply,s=Function.prototype.call,y=Function.prototype.bind||function(a,b){var c=this,d;return 1<arguments.length?(d=F.call(arguments,1),function(){return T.call(c,a,d.concat(F.call(arguments)))}):function(){return T.call(c,a,arguments)}},Z=Object.prototype.toString,R=y.call(s,Object.prototype.hasOwnProperty),
u=g.createElement("p"),j=f.Node.prototype,t=f.Element.prototype,wa=u.contains||j.contains,ha=Date,xa=/^\<([\w\:\-]*)[\>\ ]/i,ra=/^\s+/,sa=/\s/,ca,D,da=/alpha\(opacity=([^\)]+)\)/,U=function(){var a=(this.filter||"").match(da);return a?parseInt(a[1])/100+"":""},ea={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,c){"important"!=c?this.setAttribute(a,b):(c=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))",
"i"),a=";"+a+":"+b+" !important;",this.cssText=c.test(this.cssText)?this.cssText.replace(c,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||"").match(RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"))||[])[2]||""},item:K()},N={"for":"htmlFor","class":"className",value:"defaultValue"},fa={action:p,cite:p,codebase:p,data:p,href:p,longdesc:p,lowsrc:p,src:p,usemap:p,disabled:p},I={id:p,value:p,checked:p,ismap:p,multiple:p,readonly:p,selected:p},S={style:{get:function(){return this.style&&
this.style.cssText?this.style.cssText:p},set:function(a){this.style&&(this.style.cssText=a);return a},remove:function(){return this.style&&this.style.cssText?(this.style.cssText="",m):q},has:function(){return!(!this.style||!this.style.cssText)}}},x,J,G,H="uuid"+(Math.random()+"").substr(2),ya=1,za=K(),qa=q,ma,M="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|main|nav|output|progress|section|source|summary|time|video",X=M.split("|"),
ja=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,C,O,na,P,Q;"CSS1Compat"===g.compatMode?(P=function(){return r.scrollLeft},Q=function(){return r.scrollTop}):(P=function(){return g.body.scrollTop},Q=function(){return g.body.scrollLeft});g.head||(g.head=g.getElementsByTagName("head")[0]);"defaultView"in g||(g.defaultView=g.parentWindow);
e=q;try{e=isNaN.apply(p,{})}catch(Ga){}e||(Function.prototype.apply=function(a,b){var c;if(!b||!(c=+b.length))return s.call(this,a);if("object"!==typeof b||0>c||"callee"in b&&"caller"in b||"[object Array]"==Z.call(b))return T.call(this,a,b);switch(c){case 1:return s.call(this,a,b[0]);case 2:return s.call(this,a,b[0],b[1]);case 3:return s.call(this,a,b[0],b[1],b[2]);case 4:return s.call(this,a,b[0],b[1],b[2],b[3]);case 5:return s.call(this,a,b[0],b[1],b[2],b[3],b[4]);case 6:return s.call(this,a,b[0],
b[1],b[2],b[3],b[4],b[5]);case 7:return s.call(this,a,b[0],b[1],b[2],b[3],b[4],b[5],b[6])}return T.call(this,a,va(b))});"b"!=="ab".substr(-1)&&(String.prototype.substr=function(a,b){return ua.call(this,0>a?0>(a=this.length+a)?0:a:a,b)});if(2!=="ab".split(/(?:ab)*/).length||4!==".".split(/(.?)(.?)/).length||"t"==="tesst".split(/(s)*/)[1]||0==="".split(/.?/).length||1<".".split(/()()/).length)ca=/()??/.exec("")[1]===k,String.prototype.split=function(a,b){var c=this;if(!(a instanceof RegExp))return a===
k&&0===b?[]:ia.call(c,a,b);var d=[],h=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.extended?"x":"")+(a.sticky?"y":""),g=0,f,e,j;a=RegExp(a.source,h+"g");c+="";ca||(f=RegExp("^"+a.source+"$(?!\\s)",h));b=b===k?4294967295:b>>>0;if(!b)return[];for(;e=a.exec(c);){h=e.index+e[0].length;if(h>g&&(d.push(c.slice(g,e.index)),!ca&&1<e.length&&e[0].replace(f,function(){for(var a=1,b=arguments.length-2;a<b;a++)arguments[a]===k&&(e[a]=k)}),1<e.length&&e.index<c.length&&d.push.apply(d,e.slice(1)),j=e[0].length,
g=h,d.length>=b))break;a.lastIndex===e.index&&a.lastIndex++}g===c.length?(j||!a.test(""))&&d.push(""):d.push(c.slice(g));return d.length>b?d.slice(0,b):d};f.DOMException||(e=(f.DOMException=K()).prototype=Error(),e.INDEX_SIZE_ERR=1,e.HIERARCHY_REQUEST_ERR=3,e.WRONG_DOCUMENT_ERR=4,e.INVALID_CHARACTER_ERR=5,e.NO_MODIFICATION_ALLOWED_ERR=7,e.NOT_FOUND_ERR=8,e.NOT_SUPPORTED_ERR=9,e.INVALID_STATE_ERR=11,e.SYNTAX_ERR=12,e.INVALID_MODIFICATION_ERR=13,e.NAMESPACE_ERR=14,e.INVALID_ACCESS_ERR=15);"pageXOffset"in
f||n.push(function(){Object.defineProperty(f,"pageXOffset",{get:P});Object.defineProperty(f,"pageYOffset",{get:Q})});D=f.Event=function(){L("")};J={initEvent:function(a,b,c){(a==k||b==k||c==k)&&L("WRONG_ARGUMENTS_ERR");this.type=a;this.bubbles=b;this.cancelable=c;this.h=q;this.target=p;this.timeStamp||(this.timeStamp=+new ha)},initCustomEvent:function(a,b,c,d){J.initEvent.call(this,a,b,c);this.detail=d},initUIEvent:function(a,b,c,d,h){J.initCustomEvent.call(this,a,b,c,h);this.view=d},initMouseEvent:function(a,
b,c,d,h,g,f,e,j,n,l,r,s,t,u){J.initUIEvent.call(this,a,b,c,d,h);this.screenX=g;this.screenY=f;this.clientX=e;this.clientY=j;this.ctrlKey=n;this.altKey=l;this.shiftKey=r;this.metaKey=s;this.button=t;this.relatedTarget=u}};G=D.prototype={constructor:D,preventDefault:function(){this.cancelable!==q&&(x.a.call(this).returnValue=this.returnValue=q,x.d.call(this),this.defaultPrevented=m)},stopPropagation:function(){x.a.call(this).cancelBubble=this.cancelBubble=m;x.d.call(this)}};G.stopImmediatePropagation=
function(){this.__stopNow=m;this.stopPropagation()};G.defaultPrevented=q;for(e in J)R(J,e)&&(G[e]=function(){J[arguments.callee.name].apply(this,arguments);la(this.ietl9_event,this)},G[e].name=e);x=function(a){this.ietl9_event=a;a.returnValue=m;la(this,a)};x.a=function(){var a=this.ietl9_event;a===k?L("WRONG_THIS_ERR"):a===p&&(a=x.a.k);return a};x.a.k={};x.d=function(){this.ietl9_event&&(this.ietl9_event=p)};D=K();D.prototype=G;D=new D;D.constructor=x;x.prototype=D;u.addEventListener||((f.Text&&f.Text.prototype||
j).addEventListener=j.addEventListener=r.addEventListener=f.addEventListener=g.addEventListener=function(a,b,c){if("function"===typeof b||"object"===typeof b){var d=this,h=d._,e=q;d==f&&(!("_"in g)||!("_e_8vj"in g._)||!(a in g._._e_8vj))&&g.addEventListener(a,za,c);h||(h=d._={});switch(a){case "DOMContentLoaded":if("complete"==g.readyState)return;d===f&&(d=g);e=m;if(!ma){ma=m;var E=function(){try{r.doScroll("left")}catch(b){setTimeout(E,50);return}B.call(d,{type:a,isTrusted:m,__custom_event:k})};
if("createEventObject"in g&&"doScroll"in r)try{f.frameElement||E()}catch(w){}}break;case "load":"tagName"in d&&-1!="SCRIPT|IFRAME".indexOf(d.tagName.toUpperCase())&&(e=m,d.onreadystatechange=function(){"loaded"===d.readyState&&(d.onreadystatechange=p,d.attachEvent("onreadystatechange",y.call(B,d,{type:a})))},a="readystatechange");break;case "DOMMouseScroll":a="mousewheel"}d.setInterval&&(d!=f&&!d.frameElement)&&(d=f);b[H]||(b[H]=++ya);if(!(c=h._h_9e2))c=h._h_9e2=y.call(B,d);h._e_8vj||(h._e_8vj={});
a in h._e_8vj?h=h._e_8vj[a]:(h=h._e_8vj[a]=[],e||d.attachEvent("on"+a,c));"_"+b[H]in h||(h.push(b),h["_"+b[H]]=p)}},j.addEventListener.__shim__=m,(f.Text&&f.Text.prototype||j).removeEventListener=j.removeEventListener=r.removeEventListener=f.removeEventListener=g.removeEventListener=function(a,b){var c=this._,d,h,g,e,f;if(!("function"!==typeof b&&!("object"===typeof b&&b.handleEvent)||!b[H]||!c))if(d=c._h_9e2){h=c._e_8vj&&c._e_8vj[a];for(e=0;f=h[e++];)if(f===b){ba.call(h,e-1,1);delete h["_"+b[H]];
break}if(!h.length){this.detachEvent("on"+a,d);delete c._e_8vj[a];for(g in c._e_8vj)if(R(c._e_8vj,g))return;delete c._e_8vj;delete c._h_9e2}}},j.removeEventListener.__shim__=m,g.attachEvent("onmousedown",function(){A.b=event.button}),g.attachEvent("onclick",function(){A.b=k}));u.dispatchEvent||((f.Text&&f.Text.prototype||j).dispatchEvent=j.dispatchEvent=r.dispatchEvent=f.dispatchEvent=g.dispatchEvent=function(a){if(!a.type)return m;a.returnValue||(a.returnValue=m);a.cancelBubble&&(a.cancelBubble=
q);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===f||-2146827850===b.number&&!(a.bubbles=q)){a.__custom_event=m;for(var c=a.target=this,d="on"+a.type;!a.cancelBubble&&c;)(d in c&&"function"==typeof c[d]&&(a.__dom0__=c[d])||"_"in c&&"_e_8vj"in c._)&&B.call(c,a),c=a.bubbles?c===g?g.defaultView:c.parentNode:p,"__dom0__"in a&&(a.__dom0__=k,delete a.__dom0__);return!a.cancelBubble}L(b)}},j.dispatchEvent.__shim__=m);g.createEvent||(g.createEvent=function(){return new x(g.createEventObject())});
n.push(function(){function a(a){var b,c=this.nodeName.toUpperCase(),d,e,f,j,n,l,r,s;if(!("INPUT"!=c&&"TEXTAREA"!=c)){"unknown"!=typeof g.activeElement&&(l=g.activeElement);b=g.selection;this._&&(r=this._.__stop_events__,this._.__stop_events__=m);l&&l._&&(s=l._.__stop_events__,l._.__stop_events__=m);try{this.focus(),d=b.createRange(),e=d.duplicate(),"TEXTAREA"==c?(f=this.value,d=e,a?(d.moveEnd("character",f.length),n=""==d.text?f.length:f.lastIndexOf(d.text)):(d.moveStart("character",-f.length),n=
d.text.length)):(e.moveToElementText(this),e.setEndPoint("EndToEnd",d),j=e.text.length-d.text.length,n=a?j:j+d.text.length),l&&l.focus&&l.focus()}catch(t){n=k}this._&&!r&&delete this._.__stop_events__;l&&(l._&&!s)&&delete l._.__stop_events__;return n}}function b(a,b){if(a!=k){b==k&&(b=a);var c=this.nodeName.toUpperCase();"INPUT"!=c&&"TEXTAREA"!=c||(c=this.createTextRange(),c.collapse(m),c.moveStart("character",a),c.moveEnd("character",b),c.select())}}var c=f.HTMLTextAreaElement&&f.HTMLTextAreaElement.prototype,
d={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,m)},set:function(c){b.call(this,c,a.call(this));return c}},selectionEnd:{get:function(){return a.call(this)},set:function(c){b.call(this,a.call(this,m),c);return c}}};Object.defineProperties(f.HTMLInputElement&&f.HTMLInputElement.prototype||t,d);c&&Object.defineProperties(c,d)});8>v&&(t.ielt8=m);g.doctype===p&&7<v&&n.push(function(){var a=g.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});
Object.defineProperty(g,"doctype",{configurable:m,enumerable:q,get:function(){return a}})});j.contains||(j.contains=wa);s.call(aa,g,"").contains||(f.Text&&f.Text.prototype?n.push(y.call(z,p,Text.prototype,j)):function(){var a;try{a=s.call(aa,this,"a"),a.contains=K()}catch(b){return q}return m}()&&(g.createTextNode=function(a){a=s.call(aa,this,a);a.contains=j.contains;return a}));!s.call($,g).contains&&(f.HTMLDocument&&f.HTMLDocument.prototype)&&n.push(y.call(z,p,f.HTMLDocument.prototype,j));"children"in
u||n.push(function(){Object.defineProperty(t,"children",{get:function(){for(var a=[],b=this.firstChild;b;)1==b.nodeType&&a.push(b),b=b.nextSibling;return a}})});n.push(function(){function a(a,c){var d;try{a:{var h=a;"element"in h&&("defaults"in h&&"document"in h)&&(h=h.element);var e=h.getBoundingClientRect(),f,j,l;if((l=h.ownerDocument)!==g){if(f=l&&l.body,j=l&&l.documentElement,!f||!j){d=c?e.left:e.top;break a}}else f=g.body,j=r;d=c?e.left+P()-(j.clientLeft||f.clientLeft||0):e.top+Q()-(j.clientTop||
f.clientTop||0)}}catch(n){d=a;h=0;for(e=c?"offsetLeft":"offsetTop";d;)h+=parseInt(d[e],10),d=d.offsetParent;d=h}return d}Object.defineProperties(t,{offsetLeft:{get:function(){return a(this,m)}},offsetTop:{get:function(){return a(this)}}})});u.childElementCount==k&&n.push(function(){Object.defineProperties(t,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;
return a}},nextElementSibling:{get:function(){for(var a=this;(a=a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=this;(a=a.previousSibling)&&1!=a.nodeType;);return a}}})});g.ELEMENT_NODE||(e={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},z(g,e),z(j,e),z(f.Node,e));"textContent"in u||n.push(function(){Object.defineProperty(j,"textContent",{get:function(){if("innerText"in
this)return this.innerText;if("data"in this&&this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in this&&this.replaceData&&this.replaceData(0,this.length,a);return a}})});"isEqualNode"in u||(g.isEqualNode=r.isEqualNode=j.isEqualNode=function(a){var b,c;if(a===p||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return q;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=
a.prefix||this.localName!=a.localName)return q;b=0;for(c=this.attributes.length;b<c;b++){var d=this.attributes[length],e=a.getAttributeNS(d.namespaceURI,d.localName);if(e===p||e.value!==d.value)return q}}if(7===a.nodeType&&(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return q;b=0;for(c=a.childNodes.length;b<c;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===q)return q;return m});g.importNode||
(g.importNode=function(a,b){switch(a.nodeType){case 1:var c=g.createElement(a.nodeName),d=a.attributes,e,f,j;if(d&&0<d.length){f=0;for(j=d.length;f<j;)d=a.attributes[f++],c.setAttribute(d.nodeName,a.getAttribute(d.nodeName))}if(b&&(e=a.childNodes)&&0<e.length){f=0;for(j=e.length;f<j;)c.appendChild(g.importNode(e[f++],b))}return c;case 3:case 4:case 8:return g.createTextNode(a.nodeValue)}ka("NOT_SUPPORTED_ERR");return p},g.importNode.shim=m);e="compareDocumentPosition";if(!(e in g)){var l,n=l||"DOCUMENT_POSITION_";
r[e]=g[e]=j[e]=function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&4)+(this.sourceIndex>a.sourceIndex&&2):1)+0:0};l="DISCONNECTED";r[n+l]=g[n+l]=j[n+l]=1;l="PRECEDING";r[n+l]=g[n+l]=j[n+l]=2;l="FOLLOWING";r[n+l]=g[n+l]=j[n+l]=4;l="CONTAINS";r[n+l]=g[n+l]=j[n+l]=8;l="CONTAINED_BY";r[n+l]=g[n+l]=j[n+l]=16}f.getComputedStyle||(f.getComputedStyle=function(a){var b=a.currentStyle||a.runtimeStyle;
"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=y.call(ea.getPropertyValue,a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=f.getComputedStyle.j,a.runtimeStyle.getPropertyPriority=f.getComputedStyle.i,a.runtimeStyle.item=ea.item);var c,d,e;(d=f.CSSStyleDeclaration)&&(d=d.prototype)&&(!("float"in b)||!("opacity"in b))?("float"in b||((c=Object.getOwnPropertyDescriptor(d,"float"))&&delete d["float"],e=y.call(f.getComputedStyle.e,a),Object.defineProperty(a.runtimeStyle,"float",{value:{valueOf:e,
toString:e},configurable:m,writable:m}),c&&Object.defineProperty(d,"float",c)),"opacity"in b||((c=Object.getOwnPropertyDescriptor(d,"opacity"))&&"opacity"in d&&delete d.opacity,e=y.call(f.getComputedStyle.f,a),Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:e,toString:e},configurable:m,writable:m}),c&&Object.defineProperty(d,"opacity",c))):("float"in b||(e=y.call(f.getComputedStyle.e,a),a.runtimeStyle["float"]={valueOf:e,toString:e}),"opacity"in b||(e=y.call(f.getComputedStyle.f,a),
a.runtimeStyle.opacity={valueOf:e,toString:e}));return a.currentStyle},f.getComputedStyle.f=function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||U.call(this.style)||U.call(this.runtimeStyle)},f.getComputedStyle.e=function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},f.getComputedStyle.j=function(){ka("NO_MODIFICATION_ALLOWED_ERR")},f.getComputedStyle.i=function(){return""});g.createDocumentFragment=function(){var a=s.call($,this);f.DocumentFragment===f.Document&&z(a,
f.DocumentFragment.prototype);return Y(a)};e=(u.innerHTML="<x-x></x-x>",1===u.childNodes.length&&1===u.childNodes[0].nodeType);M="|"+M+"|";V.ielt9=m;C=Y(s.call($,g));e||(Y(g),g.head.insertAdjacentHTML("beforeend","<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section,main{display:block}mark{background:#FF0;color:#000}</style>"));0===s.call(W,g,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(O=C.appendChild("createElement"in C&&C.createElement("div")||C.ownerDocument.createElement("div")),
na=8===v?u.cloneNode:8>v?j.cloneNode:k,j.cloneNode=function(a){var b,c;ja.test(this.nodeName)?b=s.call(this.__nativeCloneNode__||na,this,a):(O.innerHTML="",c=a?this.outerHTML:this.outerHTML.replace(/<(\w+)([^>]*)>[\W\w]*$/,"<$1$2></$1>"),O.innerHTML=c.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=O.firstChild,!b&&!a&&((c=c.match(xa))&&(c=c[1]),c&&(C.createElement(c),O.innerHTML=c,b=O.firstChild)));return C.appendChild(b)});u=function(a){for(var b=[];a--;)b.unshift(a);return b};v=[];y.call(v.splice,
v,0,0).apply(p,u(20));y.call(v.splice,v,0,0).apply(p,u(26));u=v.length;v.splice(5,0,"XXX");v=u+1==v.length?m:k;v||(Array.prototype.splice=function(a,b){var c,d=F.call(arguments,2);c=d.length;if(!arguments.length)return[];a===k&&(a=0);b===k&&(b=this.length-a);if(0<c){if(0>=b){if(a==this.length)return this.push.apply(this,d),[];if(0==a)return this.unshift.apply(this,d),[]}c=F.call(this,a,a+b);d.push.apply(d,F.call(this,a+b,this.length));d.unshift.apply(d,F.call(this,0,a));d.unshift(0,this.length);ba.apply(this,
d);return c}return ba.call(this,a,b)});var Aa=/\s+(?=\S)|^/g,ga=t.getAttribute,Ba=t.setAttribute,oa=t.removeAttribute;I.g={};I.c=function(a,b){if(b in this)return m;var c=a.nodeName;if(!(a=I.g[c]))a=I.g[c]=W(c);c=ga.call(a,b)!==p;c||(c=(c=a.constructor)&&(c=c.prototype)&&"object"===typeof(c=Object.getOwnPropertyDescriptor(c,b))&&"get"in c&&/\[native\scode\]/.test(c.get+""));return this[b]=c};t.setAttribute=function(a,b){var c=a.toLowerCase(),d=a,e,f;if(c in S)return S[c].set.call(this,b);N[c]!==k?
d=N[c]:fa[c]===k&&(-1===c.indexOf("-")&&!I.c(this,c))&&(d=a.toUpperCase());d!=a&&a in this&&(!(f=this.attributes)||!((f=f[a])&&f.expando===q))?(f=this[a],e=m):f=p;b+="";d!=a?(this[d]=b,e&&(this[a]=f)):Ba.call(this,d,b)};t.getAttribute=function(a){var b;b=a.toLowerCase();var c;if((c=S[b])!==k)return c.get.call(this);if(N[b]!==k)return ga.call(this,N[b]);if(fa[b]!==k)return(c=this.attributes)&&(c=c[b])&&(c=c.nodeValue)&&c+""||p;if(-1===b.indexOf("-")&&!I.c(this,b))b=a.toUpperCase();else return ga.call(this,
a);c=this[b];c||(!(b in this)&&"string"===typeof this[a]?(c=this[b]=this[a],delete this[a]):c=k);return c!==k?c+"":p};t.removeAttribute=function(a){var b;b=a.toLowerCase();var c;if(b in S)return S[b].remove.call(this);if(N[b]!==k)return oa.call(this,N[b]);if(fa[b]===k&&-1===b.indexOf("-")&&!I.c(this,b))b=a.toUpperCase();else return oa.call(this,a);((c=b in this)||this.getAttribute(a)!==p)&&b in this&&delete this[b];return c};t.hasAttribute=function(a){return this.getAttribute(a)!==p};e="getElementsByClassName";
!t[e]&&g.querySelectorAll&&(t[e]=r[e]=g[e]=function(a){return!a||!(a=ta.call(a))?[]:s.call(this.querySelectorAll||g.querySelectorAll,this,a.replace(Aa,"."))});if(e=f.CSSStyleDeclaration)"opacity"in r.style||(Object.defineProperty(e.prototype,"opacity",{get:U,set:function(a){"object"==typeof a&&(a=a.valueOf());this.opacity!==U.call(this)&&delete this.opacity;a=a&&"alpha(opacity="+(0.9999<=a?"100":0>a?0:~~(100*a))+")"||"";this.filter=da.test(this.filter)?this.filter.replace(da,a):this.filter+(" "+a);
this.msOpacity=this.opacity}}),Object.defineProperty(e.prototype,"msOpacity",{value:""})),"float"in r.style||Object.defineProperty(e.prototype,"float",{get:function(){return this.styleFloat},set:function(a){return this.styleFloat=a}}),"getPropertyValue"in e||function(a){for(var b in a)R.call(a,b)&&(this[b]=a[b])}.call(e,ea);if((e=f.TextRectangle)&&(e=e.prototype))Object.defineProperty(e,"width",{get:function(){return this.right-this.left}}),Object.defineProperty(e,"height",{get:function(){return this.bottom-
this.top}});var Ca=g.querySelectorAll,Da=g.querySelector,Ea=t.querySelectorAll,Fa=t.querySelector,pa=function(a){for(var b=a.length>>>0,c=[],d=0;d<b;d++)d in a&&c.push(a[d]);return c};g.querySelectorAll=function(){return pa(Ca.apply(this,arguments))};g.querySelector=function(){return Da.apply(this,arguments)};t.querySelectorAll=function(){return pa(Ea.apply(this,arguments))};t.querySelector=function(){return Fa.apply(this,arguments)};u=e=D=e=p}}.call(window,function(z,A){for(var B in A)Object.prototype.hasOwnProperty.call(A,
B)&&!Object.prototype.hasOwnProperty.call(z,B)&&(z[B]=A[B]);return z});
